{
  "hash": "37ce150a9c611a2fb93098b924ddd58d",
  "result": {
    "engine": "knitr",
    "markdown": "# Sistemas de coordenadas {#sec-m2-crs}\n\nEste é o capítulo mais curto e o que evita mais erros. Quase todo problema de \"as camadas não\nse sobrepõem\", \"a área saiu errada\" ou \"o *buffer* ficou oval\" é problema de projeção.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(sf)\nlibrary(dplyr)\nlibrary(ggplot2)\n```\n:::\n\n\n## Os dois tipos de sistema\n\n**Geográfico** (graus): coordenadas de latitude e longitude sobre um elipsoide. Bom para\nguardar e trocar dados; ruim para medir.\n\n**Projetado** (metros): a superfície curva achatada em um plano. Bom para medir distâncias,\náreas e fazer *buffers*; introduz distorção que cresce com a extensão da área.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|  epsg|nome                           |tipo       |uso                                     |\n|-----:|:------------------------------|:----------|:---------------------------------------|\n|  4326|WGS 84                         |geográfico |GPS, OSM, GTFS, arquivos internacionais |\n|  4674|SIRGAS 2000                    |geográfico |padrão oficial brasileiro (IBGE, DNIT)  |\n| 31982|SIRGAS 2000 / UTM 22S          |projetado  |PR, SC, oeste de SP                     |\n| 31983|SIRGAS 2000 / UTM 23S          |projetado  |SP, RJ, MG, GO                          |\n| 31984|SIRGAS 2000 / UTM 24S          |projetado  |CE, BA, PE (Fortaleza)                  |\n|  5880|SIRGAS 2000 / Brazil Polyconic |projetado  |mapas do Brasil inteiro                 |\n\n\n:::\n:::\n\n\n::: {.callout-note}\n## Qual usar no Ministério\n\n- Para **guardar e distribuir** dados: SIRGAS 2000 (`EPSG:4674`). É o sistema geodésico\n  oficial do Brasil. Dados vindos de GPS, OSM ou GTFS chegam em WGS 84 (`EPSG:4326`); na\n  prática a diferença entre os dois é de poucos centímetros, mas declare o correto.\n- Para **medir** em escala local ou regional: a zona UTM correspondente.\n- Para **mapas nacionais**: Policônica do Brasil (`EPSG:5880`) ou uma projeção de áreas\n  iguais (Albers), definida adiante.\n:::\n\n::: {.callout-tip}\n## Onde consultar um EPSG que não está nessa tabela\n\n<https://epsg.io/> aceita busca por nome de lugar, código ou palavra-chave, e mostra a área de\nuso, a unidade e o código pronto para colar (`EPSG:xxxx`). O `sf` também expõe a mesma base\nlocalmente, sem depender de internet:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsf::st_crs(\"EPSG:31982\")            # detalhes completos de um código conhecido\nsf::st_crs(32722)                   # aceita o número puro também\n```\n:::\n\n:::\n\n## Consultar, definir e transformar\n\nSão três operações diferentes, e confundi-las é o erro mais comum.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nportos <- data.frame(\n  nome = c(\"Paranaguá\", \"Itajaí\"),\n  lon  = c(-48.5119, -48.6486),\n  lat  = c(-25.5016, -26.9077)\n) |>\n  sf::st_as_sf(coords = c(\"lon\", \"lat\"), crs = 4326)\n\n# 1. CONSULTAR: qual é o CRS?\nsf::st_crs(portos)$input\n#> [1] \"EPSG:4326\"\nsf::st_crs(portos)$epsg\n#> [1] 4326\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 2. DEFINIR: informar qual é o CRS de um dado que veio sem essa informação.\n#    NÃO move as coordenadas, apenas rotula.\nsem_crs <- sf::st_set_crs(portos, NA)\nsf::st_crs(sem_crs)$input\n#> [1] NA\n\ncorrigido <- sf::st_set_crs(sem_crs, 4326)\nsf::st_crs(corrigido)$epsg\n#> [1] 4326\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 3. TRANSFORMAR: converter as coordenadas para outro sistema.\n#    MOVE as coordenadas, recalculando-as.\nportos_utm <- sf::st_transform(portos, 31982)\nsf::st_crs(portos_utm)$epsg\n#> [1] 31982\nsf::st_coordinates(portos_utm)\n#>             X       Y\n#> [1,] 750094.3 7177170\n#> [2,] 733523.7 7021618\n```\n:::\n\n\nCompare as coordenadas: em UTM são metros a partir do meridiano central da zona, na casa das\ncentenas de milhares. Em graus eram números entre -49 e -25.\n\n::: {.callout-important}\n## `st_set_crs()` nunca conserta uma sobreposição errada\n\nSe duas camadas não se alinham, o reflexo errado é `st_set_crs()`. Ele só troca o rótulo e\ndeixa as coordenadas no lugar errado. O certo é `st_transform()`. Use `st_set_crs()`\n**exclusivamente** quando o dado chegou sem CRS e você sabe, por documentação, qual é.\n:::\n\n## Quando reprojetar é obrigatório\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# distância entre dois portos, em coordenadas geográficas\nsf::st_distance(portos[1, ], portos[2, ])\n#> Units: [m]\n#>          [,1]\n#> [1,] 156945.1\n```\n:::\n\n\nO `sf` moderno usa a biblioteca `s2` e calcula distâncias **geodésicas** corretas mesmo em\ngraus. Para distância, hoje você não precisa reprojetar.\n\nCom *buffer* a história é mais delicada. Em dados projetados, `dist` está na unidade do CRS\n(metros, em UTM). Em coordenadas geográficas, o `sf` também aceita metros, porque delega ao\n`s2`. O resultado, porém, é uma **aproximação por células esféricas**, mais lenta e menos\nprevisível em bordas:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nb_graus  <- sf::st_buffer(portos[1, ], dist = 10000)                    # via s2, em metros\nb_metros <- portos[1, ] |> sf::st_transform(31982) |> sf::st_buffer(10000)  # plano, em metros\n\nc(\n  s2_km2  = as.numeric(units::set_units(sf::st_area(b_graus),  km^2)),\n  utm_km2 = as.numeric(units::set_units(sf::st_area(b_metros), km^2))\n)\n#>   s2_km2  utm_km2 \n#> 318.1793 314.0157\n```\n:::\n\n\nUm *buffer* de 10 km deve ter área próxima de π × 10² ≈ 314 km². Confira sempre por essa conta\nde cabeça: é a verificação mais rápida de que a projeção estava certa. A conferência visual\najuda a enxergar a diferença entre as duas abordagens:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmapview::mapview(b_graus, col.regions = \"#1a5b8a\") +\n  mapview::mapview(b_metros, col.regions = \"#b3402a\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"leaflet html-widget html-fill-item\" id=\"htmlwidget-8d893f54a0f078fc561e\" style=\"width:100%;height:406px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-8d893f54a0f078fc561e\">{\"x\":{\"options\":{\"minZoom\":1,\"maxZoom\":52,\"crs\":{\"crsClass\":\"L.CRS.EPSG3857\",\"code\":null,\"proj4def\":null,\"projectedBounds\":null,\"options\":{}},\"preferCanvas\":false,\"bounceAtZoomLimits\":false,\"maxBounds\":[[[-90,-370]],[[90,370]]]},\"calls\":[{\"method\":\"addProviderTiles\",\"args\":[\"CartoDB.Positron\",\"CartoDB.Positron\",\"CartoDB.Positron\",{\"errorTileUrl\":\"\",\"noWrap\":false,\"detectRetina\":false,\"pane\":\"tilePane\"}]},{\"method\":\"addProviderTiles\",\"args\":[\"CartoDB.DarkMatter\",\"CartoDB.DarkMatter\",\"CartoDB.DarkMatter\",{\"errorTileUrl\":\"\",\"noWrap\":false,\"detectRetina\":false,\"pane\":\"tilePane\"}]},{\"method\":\"addProviderTiles\",\"args\":[\"OpenStreetMap\",\"OpenStreetMap\",\"OpenStreetMap\",{\"errorTileUrl\":\"\",\"noWrap\":false,\"detectRetina\":false,\"pane\":\"tilePane\"}]},{\"method\":\"addProviderTiles\",\"args\":[\"Esri.WorldImagery\",\"Esri.WorldImagery\",\"Esri.WorldImagery\",{\"errorTileUrl\":\"\",\"noWrap\":false,\"detectRetina\":false,\"pane\":\"tilePane\"}]},{\"method\":\"addProviderTiles\",\"args\":[\"OpenTopoMap\",\"OpenTopoMap\",\"OpenTopoMap\",{\"errorTileUrl\":\"\",\"noWrap\":false,\"detectRetina\":false,\"pane\":\"tilePane\"}]},{\"method\":\"createMapPane\",\"args\":[\"polygon\",420]},{\"method\":\"addPolygons\",\"args\":[[[[{\"lng\":[-48.43875773234157,-48.43875773234157,-48.44000629646233,-48.44000629646233,-48.44125488891167,-48.44125488891167,-48.44219135183889,-48.44219135183889,-48.4425035096889,-48.4425035096889,-48.44312783070027,-48.44312783070027,-48.44375215879334,-48.44375215879334,-48.44375215879334,-48.44500083622426,-48.44500083622426,-48.44624954198098,-48.44624954198098,-48.4474982760628,-48.44749827606279,-48.44859094161926,-48.44859094161926,-48.448747038469,-48.448747038469,-48.44968362886112,-48.44968362886112,-48.4499958291989,-48.4499958291989,-48.45093244083334,-48.45093244083335,-48.45124464825182,-48.45124464825182,-48.45186906839917,-48.45186906839917,-48.45249349562701,-48.45249349562702,-48.45311792993526,-48.45311792993526,-48.45374237132381,-48.45374237132381,-48.4543668197926,-48.4543668197926,-48.45499127534151,-48.45499127534151,-48.45561573797048,-48.45561573797048,-48.4562402076794,-48.4562402076794,-48.45686468446819,-48.45686468446819,-48.45748916833679,-48.45748916833679,-48.45811365928508,-48.45811365928507,-48.45873815731297,-48.45873815731297,-48.46108008796888,-48.46108008796889,-48.46123622021892,-48.46123622021892,-48.46248529414729,-48.46248529414729,-48.46373439639164,-48.46373439639164,-48.46498352695129,-48.46498352695129,-48.46623268582552,-48.46685727588039,-48.46685727588039,-48.46748187301364,-48.46748187301363,-48.46810647722518,-48.46810647722518,-48.46873108851494,-48.46873108851494,-48.46998033232872,-48.46998033232872,-48.47122960445427,-48.47122960445428,-48.47310356572566,-48.47310356572567,-48.47372823363792,-48.47372823363792,-48.47493854785807,-48.47493854785807,-48.4749775906946,-48.4749775906946,-48.47622697606024,-48.47622697606025,-48.47747638973415,-48.47841346856646,-48.47841346856646,-48.47872583171561,-48.47872583171561,-48.47997530200394,-48.47997530200394,-48.48122480059842,-48.48216194311976,-48.48216194311976,-48.48247432749835,-48.48247432749835,-48.48372388270302,-48.48372388270302,-48.48497346621172,-48.48622307802376,-48.48622307802376,-48.48809754880904,-48.48809754880904,-48.48872238655504,-48.48872238655504,-48.48997208327285,-48.4905969422445,-48.4905969422445,-48.49122180829119,-48.49122180829119,-48.49247156160934,-48.49247156160933,-48.49372134322658,-48.49497115314222,-48.49497115314222,-48.49622099135556,-48.49747085786588,-48.49747085786588,-48.49872075267248,-48.49997067577465,-48.49997067577465,-48.50122062717169,-48.50309560731857,-48.50309560731857,-48.50372061484753,-48.50372061484754,-48.50497065112493,-48.50618165074832,-48.50618165074832,-48.50622071569435,-48.50622071569436,-48.5087209297065,-48.50934600089095,-48.50934600089095,-48.5099710791478,-48.5099710791478,-48.5112212568783,-48.5124714628973,-48.5124714628973,-48.51372169720408,-48.51622225067818,-48.51622225067819,-48.5174725698441,-48.51872291729494,-48.51997329303004,-48.52091109339248,-48.52091109339248,-48.52122369704868,-48.52122369704868,-48.52372458993371,-48.52618651685547,-48.52618651685547,-48.52622559594435,-48.52622559594435,-48.52685086512223,-48.52747614137,-48.52747614137,-48.52872671507493,-48.52997731705842,-48.53122794731976,-48.53247860585824,-48.53247860585824,-48.53372929267316,-48.53623075112941,-48.53873232268285,-48.54123400732777,-48.54373580505846,-48.54623771586923,-48.54873973975437,-48.55124187670818,-48.55374412672493,-48.55624648979892,-48.55874896592444,-48.56125155509575,-48.56125155509575,-48.5625028920718,-48.56375425730715,-48.56500565080108,-48.56625707255289,-48.56625707255289,-48.56688279402528,-48.56688279402528,-48.56876000082726,-48.57001150734839,-48.57001150734839,-48.57063727120463,-48.57063727120463,-48.57095015578162,-48.57095015578162,-48.57126304212454,-48.57251460515496,-48.57376619643896,-48.57376619643896,-48.57439200267583,-48.57439200267583,-48.57626946376481,-48.57752113980523,-48.57752113980523,-48.57877284409635,-48.58002457663746,-48.58002457663746,-48.58127633742782,-48.58252812646675,-48.58252812646675,-48.58377994375351,-48.58377994375351,-48.58440586298959,-48.58440586298959,-48.58628366306763,-48.58628366306763,-48.58753556509357,-48.58753556509357,-48.58816152669844,-48.58816152669844,-48.58878749536446,-48.59003945387958,-48.59003945387958,-48.59129144063823,-48.59129144063823,-48.59254345563967,-48.59254345563966,-48.59379549888319,-48.59379549888319,-48.59504757036807,-48.59504757036807,-48.59629967009357,-48.59629967009357,-48.59755179805901,-48.59755179805901,-48.59880395426363,-48.59880395426363,-48.59880395426363,-48.59943004295542,-48.59943004295542,-48.60005613870673,-48.60005613870673,-48.60009526992559,-48.60009526992559,-48.60130835138759,-48.60130835138759,-48.60256059230548,-48.60256059230547,-48.60256059230548,-48.60381286145968,-48.60381286145969,-48.60381286145968,-48.60412593316008,-48.60412593316008,-48.60506515884948,-48.60506515884948,-48.60506515884947,-48.60537823760865,-48.60537823760865,-48.60631748447414,-48.60631748447414,-48.60631748447414,-48.60756983833295,-48.60756983833296,-48.60756983833296,-48.60756983833296,-48.60819602584994,-48.60819602584994,-48.60882222042518,-48.60882222042518,-48.60882222042519,-48.60913532035963,-48.60913532035963,-48.61007463075013,-48.61007463075013,-48.61007463075012,-48.61007463075012,-48.61007463075012,-48.61132706930705,-48.61132706930704,-48.61132706930705,-48.61132706930704,-48.61132706930705,-48.61257953609523,-48.61257953609523,-48.61257953609523,-48.61257953609523,-48.61257953609523,-48.61257953609523,-48.61257953609523,-48.61257953609523,-48.61257953609523,-48.61257953609523,-48.61257953609523,-48.61164018335744,-48.61164018335744,-48.61132706930704,-48.61132706930704,-48.61132706930705,-48.61132706930705,-48.61132706930705,-48.61070084649963,-48.61070084649963,-48.61007463075012,-48.61007463075013,-48.61007463075013,-48.61007463075012,-48.61007463075012,-48.61007463075012,-48.60913532035963,-48.60913532035963,-48.60882222042518,-48.60882222042518,-48.60882222042518,-48.60882222042519,-48.60764811138657,-48.60764811138657,-48.60756983833295,-48.60756983833296,-48.60756983833296,-48.60756983833295,-48.60694365787432,-48.60694365787433,-48.60631748447414,-48.60631748447414,-48.60631748447414,-48.60569131813249,-48.60569131813249,-48.60506515884948,-48.60506515884948,-48.60506515884948,-48.60506515884948,-48.60382264492361,-48.60382264492361,-48.60381286145968,-48.60381286145968,-48.60318672335309,-48.60318672335309,-48.60256059230547,-48.60256059230547,-48.60256059230548,-48.60256059230548,-48.60130835138759,-48.60130835138759,-48.60130835138759,-48.60005613870673,-48.60005613870673,-48.60005613870673,-48.59888221496404,-48.59888221496404,-48.59880395426363,-48.59880395426363,-48.59880395426363,-48.59757136278253,-48.59757136278253,-48.597551798059,-48.59755179805901,-48.59755179805901,-48.59629967009358,-48.59629967009357,-48.59629967009358,-48.59504757036807,-48.59504757036806,-48.5944215310955,-48.5944215310955,-48.59379549888319,-48.59379549888319,-48.59269995950064,-48.59269995950064,-48.59254345563967,-48.59254345563967,-48.59254345563967,-48.59129144063823,-48.59129144063823,-48.59035244792145,-48.59035244792145,-48.59003945387958,-48.59003945387958,-48.59003945387958,-48.58878749536446,-48.58878749536446,-48.58784854501336,-48.58784854501336,-48.58753556509356,-48.58753556509357,-48.58753556509357,-48.58628366306763,-48.58628366306763,-48.58504156944181,-48.58504156944181,-48.58503178928737,-48.58503178928737,-48.5844058629896,-48.5844058629896,-48.58377994375351,-48.58377994375351,-48.58252812646675,-48.58252812646675,-48.58127633742782,-48.58127633742782,-48.5803375141867,-48.5803375141867,-48.58002457663746,-48.58002457663745,-48.5793987068357,-48.5793987068357,-48.57877284409635,-48.57877284409635,-48.57877284409635,-48.57752113980523,-48.57752113980523,-48.57626946376481,-48.57626946376481,-48.57501781597582,-48.57501781597582,-48.57376619643896,-48.57376619643896,-48.57141948595819,-48.5714194859582,-48.57126304212454,-48.57126304212453,-48.57016794765023,-48.57016794765023,-48.5700115073484,-48.57001150734839,-48.56891643759718,-48.56891643759718,-48.56876000082726,-48.56876000082726,-48.56641350225871,-48.56641350225871,-48.56625707255289,-48.56625707255289,-48.56375425730715,-48.56375425730715,-48.5625028920718,-48.5625028920718,-48.56125155509575,-48.56125155509575,-48.56000024637972,-48.56000024637972,-48.55874896592443,-48.55812333629479,-48.55812333629479,-48.55749771373059,-48.55749771373059,-48.55655929313222,-48.55655929313222,-48.55624648979892,-48.55624648979892,-48.55499529413013,-48.55499529413013,-48.55374412672493,-48.55374412672493,-48.55186742861294,-48.55186742861294,-48.55124187670818,-48.55124187670818,-48.54873973975437,-48.54873973975437,-48.54748871367786,-48.54686321124002,-48.54686321124002,-48.54623771586923,-48.54623771586922,-48.54498674632919,-48.54498674632919,-48.54373580505846,-48.5431103450243,-48.5431103450243,-48.54248489205775,-48.54248489205774,-48.54123400732777,-48.54123400732777,-48.53998315086923,-48.53904502707889,-48.53904502707889,-48.53873232268285,-48.53873232268285,-48.53748152276934,-48.53748152276934,-48.53623075112942,-48.53498000776378,-48.53498000776378,-48.53372929267315,-48.53263494016375,-48.53263494016375,-48.53247860585824,-48.53247860585824,-48.53122794731976,-48.53028997197273,-48.53028997197273,-48.52997731705842,-48.52997731705842,-48.52872671507493,-48.52810142468761,-48.52810142468761,-48.52747614137,-48.52747614137,-48.52622559594435,-48.52560033383647,-48.52560033383647,-48.52497507879868,-48.52497507879868,-48.52372458993371,-48.52278674184461,-48.52278674184461,-48.52247412935014,-48.52247412935014,-48.52122369704868,-48.51997329303004,-48.51997329303004,-48.51872291729494,-48.51684740672547,-48.51684740672547,-48.51622225067819,-48.51622225067819,-48.51497195979795,-48.51372169720408,-48.51372169720408,-48.51004921442717,-48.51004921442718,-48.5099710791478,-48.5099710791478,-48.50872092970649,-48.50747080855511,-48.50622071569435,-48.50622071569435,-48.50372061484754,-48.50184561348055,-48.50184561348056,-48.50122062717169,-48.50122062717169,-48.49997067577465,-48.49872075267248,-48.49747085786588,-48.49637722312187,-48.49637722312187,-48.49622099135556,-48.49622099135556,-48.49372134322658,-48.48934723137634,-48.48934723137634,-48.48872238655504,-48.48872238655504,-48.48747271813844,-48.48622307802376,-48.48497346621172,-48.48372388270302,-48.48247432749835,-48.48122480059842,-48.47997530200394,-48.47872583171561,-48.47747638973415,-48.47622697606024,-48.4749775906946,-48.47372823363792,-48.47247890489091,-48.47122960445427,-48.46998033232872,-48.46873108851494,-48.46748187301364,-48.46623268582552,-48.46498352695129,-48.46373439639164,-48.46373439639164,-48.45873815731296,-48.45748916833679,-48.45748916833679,-48.4562402076794,-48.45499127534151,-48.45374237132381,-48.45374237132381,-48.45311792993526,-48.45311792993526,-48.45124464825181,-48.4499958291989,-48.44999582919891,-48.44983972880874,-48.44983972880875,-48.448747038469,-48.44749827606279,-48.44624954198098,-48.44624954198098,-48.44375215879334,-48.44375215879334,-48.4425035096889,-48.44125488891167,-48.44125488891167,-48.44000629646233,-48.44000629646233,-48.4396941527763,-48.4396941527763,-48.43875773234157,-48.4375091965501,-48.4375091965501,-48.43626068908862,-48.43626068908861,-48.43594856664989,-48.43594856664989,-48.43501220995782,-48.43501220995782,-48.43438798101664,-48.43438798101664,-48.4337637591584,-48.43251533669106,-48.43251533669107,-48.4312669425565,-48.4312669425565,-48.43001857675542,-48.43001857675542,-48.4287702392885,-48.4287702392885,-48.42752193015644,-48.42752193015645,-48.42627364935996,-48.42627364935996,-48.42502539689974,-48.42502539689974,-48.42502539689974,-48.42440128129594,-48.42440128129594,-48.42377717277648,-48.42377717277648,-48.42375766949939,-48.42375766949939,-48.42252897699086,-48.42252897699085,-48.42128080954359,-48.42128080954359,-48.42003267043537,-48.42003267043537,-48.42003267043537,-48.41972064008637,-48.41972064008637,-48.41878455966689,-48.4187845596669,-48.41847253640293,-48.41847253640294,-48.41753647723885,-48.41753647723885,-48.41753647723885,-48.41628842315194,-48.41628842315194,-48.41628842315194,-48.41566440673662,-48.41566440673662,-48.41504039740685,-48.41504039740684,-48.41504039740684,-48.41504039740685,-48.41441639516271,-48.41441639516271,-48.41379240000428,-48.41379240000428,-48.41379240000428,-48.41348040508224,-48.41348040508224,-48.41254443094493,-48.41254443094493,-48.41254443094493,-48.41254443094493,-48.41254443094493,-48.41254443094493,-48.41254443094493,-48.41254443094493,-48.41223244310881,-48.41223244310881,-48.41129649022949,-48.41129649022949,-48.4112964902295,-48.4112964902295,-48.4112964902295,-48.41129649022949,-48.41129649022949,-48.412543212239,-48.41254321223901,-48.41254443094493,-48.41254443094493,-48.41254443094493,-48.41254443094493,-48.41254443094493,-48.41254443094493,-48.41254443094493,-48.41254443094493,-48.41254443094493,-48.41379240000428,-48.41379240000428,-48.41379240000428,-48.41504039740685,-48.41504039740684,-48.41504039740685,-48.41504039740684,-48.41566440673662,-48.41566440673662,-48.41628842315193,-48.41628842315194,-48.41628842315194,-48.41753647723885,-48.41753647723885,-48.41753647723885,-48.41753647723885,-48.41878455966689,-48.41878455966689,-48.4187845596669,-48.41940861150862,-48.41940861150862,-48.42003267043537,-48.42003267043537,-48.42003267043537,-48.42003267043537,-48.42128080954359,-48.42128080954359,-48.42245096569517,-48.42245096569517,-48.42252897699085,-48.42252897699085,-48.42252897699086,-48.42346512117338,-48.42346512117339,-48.42377717277648,-48.42377717277648,-48.42440128129594,-48.42440128129594,-48.42502539689973,-48.42502539689974,-48.42502539689974,-48.42596158358835,-48.42596158358835,-48.42627364935996,-48.42627364935996,-48.42736589350727,-48.42736589350727,-48.42752193015644,-48.42752193015645,-48.42752193015644,-48.4287702392885,-48.4287702392885,-48.43001857675542,-48.43001857675541,-48.43064275611423,-48.43064275611423,-48.4312669425565,-48.4312669425565,-48.4312669425565,-48.43251533669106,-48.43251533669106,-48.43313954438318,-48.43313954438318,-48.43376375915841,-48.4337637591584,-48.43501220995782,-48.43501220995782,-48.43563644598184,-48.43563644598184,-48.43626068908862,-48.43626068908862,-48.43626068908862,-48.4375091965501,-48.4375091965501,-48.4384455957378,-48.4384455957378,-48.43875773234157],\"lat\":[-25.44052131054107,-25.43839897677765,-25.43882837710879,-25.4376155964412,-25.43804497811412,-25.43683217994808,-25.43715420257144,-25.43685099983379,-25.43695833929985,-25.43604872729759,-25.43626339995846,-25.43565698741311,-25.43587165540869,-25.43526523848904,-25.43405240261737,-25.43448171352175,-25.43326886015387,-25.43369815239502,-25.43248528153139,-25.43291455510817,-25.43170166674926,-25.43207726500866,-25.43192565215599,-25.43197930857677,-25.43091801580677,-25.43123994335379,-25.43093671369468,-25.43104402146791,-25.43013432870324,-25.43045624224945,-25.43015300821681,-25.43026031132299,-25.42935060543797,-25.42956520537683,-25.42895873024448,-25.42917332551591,-25.4285668460103,-25.42878143661417,-25.42817495273533,-25.42838953867151,-25.4277830504195,-25.42799763168783,-25.42739113906273,-25.42760571566307,-25.42699921866492,-25.42721379059712,-25.42660728922598,-25.42682185648991,-25.42621535074584,-25.42642991334135,-25.42582340322441,-25.42603796115135,-25.4254314466616,-25.42564599991983,-25.42503948105733,-25.4252540296467,-25.42343445791769,-25.42423896487586,-25.42408733015745,-25.42414096323792,-25.42307951741096,-25.42350856692538,-25.42229546865915,-25.42272449949423,-25.42151138373873,-25.42194039589332,-25.42072726264902,-25.42115625612196,-25.42137075140024,-25.42076417267215,-25.42097866327966,-25.42037208017947,-25.42058656611606,-25.41997997864383,-25.42019445990937,-25.41958786806515,-25.42001682028113,-25.41880361977833,-25.41923255330846,-25.41801933531832,-25.41866270612325,-25.41805608502235,-25.41827053631204,-25.41766391083941,-25.41807940027651,-25.41804148571423,-25.418054888524,-25.41687953534165,-25.41730840891292,-25.4160951236675,-25.41652397854756,-25.41684561715071,-25.41654228894581,-25.41664950040169,-25.41573951200396,-25.4161683442946,-25.41495500928144,-25.41538382287781,-25.41570543051644,-25.41540208986959,-25.4155092910036,-25.41459926528028,-25.4150280562815,-25.41381467150131,-25.4142434438052,-25.41467221220745,-25.41345879514564,-25.41410191823641,-25.4134951975999,-25.41370956631248,-25.41310284130478,-25.4135315684031,-25.41374593048777,-25.41313919371053,-25.41335355111956,-25.41274680997115,-25.41317551446094,-25.41196201535156,-25.41239070113718,-25.41281938301465,-25.41160585162396,-25.41203451479535,-25.41246317405665,-25.41124961038475,-25.41167825093807,-25.4121068875794,-25.41089329162636,-25.4113219095578,-25.41196482911601,-25.41135801163571,-25.41157231249838,-25.41096549064698,-25.41139408203689,-25.41180927621059,-25.41177134891223,-25.41178474219701,-25.41060899419806,-25.4114661277961,-25.41168040874594,-25.41107355158655,-25.41128782785723,-25.41068096632669,-25.41110950852909,-25.41153804680951,-25.41032429213982,-25.41075281170123,-25.4116098390512,-25.41039603730495,-25.41082453029574,-25.41125301935956,-25.41168150449525,-25.41200286576849,-25.41169940104109,-25.41180652004959,-25.41089612208432,-25.41175304311573,-25.41259655939333,-25.41255862427708,-25.41257201328696,-25.41200298601089,-25.41221720617913,-25.41243142536359,-25.41182445488672,-25.41225288290698,-25.41268130699061,-25.41310972713648,-25.41353814334342,-25.41232414119626,-25.41275253867053,-25.41360932179536,-25.41446608914748,-25.41532284071762,-25.41617957649646,-25.41703629647472,-25.41789300064309,-25.41874968899227,-25.41960636151297,-25.42046301819587,-25.4213196590317,-25.42217628401113,-25.42339062628417,-25.42381894760802,-25.42424726496387,-25.42467557835057,-25.42510388776695,-25.42571108744975,-25.42592524436397,-25.42653244706241,-25.42717492293126,-25.42760323520963,-25.42821045570279,-25.42842461404604,-25.42872822588477,-25.4288353056073,-25.42913891819949,-25.42924599859713,-25.42967431770189,-25.43010263282853,-25.43070987412697,-25.43092403389238,-25.43153127820341,-25.4321737626111,-25.43260208057229,-25.43381660408699,-25.43424493283966,-25.43467325760758,-25.43588780793845,-25.43631614349349,-25.43674447506105,-25.43795905220158,-25.4383873945519,-25.43899468948105,-25.43920886285258,-25.43981616078942,-25.44045868599418,-25.44167330196588,-25.44210166188002,-25.44270897622118,-25.44292315837229,-25.44353047571901,-25.44374466056305,-25.44417302725392,-25.44538768203681,-25.44581605949615,-25.44703072629482,-25.44745911451986,-25.44867379333062,-25.44910219231856,-25.45031688313772,-25.45074529288579,-25.45195999570968,-25.45238841621507,-25.45360313104,-25.45403156229994,-25.45524628912223,-25.45567473113391,-25.45688946994988,-25.45749683832054,-25.45771106889121,-25.45831844025914,-25.45853267351649,-25.45970946071927,-25.45972285071126,-25.4597608115599,-25.46017589981557,-25.46139065983642,-25.46181914884067,-25.46303392084166,-25.46424869006711,-25.46467720456275,-25.46589198576219,-25.46680306983769,-25.46691020428765,-25.46721389955377,-25.46753530416296,-25.46875009455055,-25.46966118551445,-25.46976832633456,-25.47007202389617,-25.47039344761469,-25.47160824718013,-25.47282304395761,-25.47325163489131,-25.47446644362432,-25.47568124956522,-25.47628865148812,-25.47650296387732,-25.47711036878732,-25.47732468385648,-25.47975431124665,-25.48066541863162,-25.48077258592367,-25.48107628895652,-25.4813977920869,-25.48261261352172,-25.48382743215284,-25.48504224797858,-25.48625706099729,-25.48668578726633,-25.48790061221219,-25.49033025366873,-25.49275988386721,-25.49518950279433,-25.49561832816569,-25.49683314812814,-25.49804796526694,-25.49926277958043,-25.50047759106694,-25.50169239972481,-25.50290720555235,-25.50412200854793,-25.50533680870986,-25.50655160603648,-25.50776640052613,-25.50744467142956,-25.50774836684813,-25.50764112239125,-25.50976697891181,-25.51219651856612,-25.51462604684244,-25.51705556372745,-25.51684101702023,-25.51744839078108,-25.51723383938519,-25.51784120875423,-25.51905594535308,-25.52027067909824,-25.52148540998805,-25.52270013802085,-25.52237825937345,-25.52268193817648,-25.52257464386955,-25.52348567644807,-25.52591508879181,-25.5271297906702,-25.52672738305201,-25.52680330096242,-25.52677647360417,-25.52791524005578,-25.52912992149496,-25.53034460006707,-25.53012995902952,-25.53073729356307,-25.5305226478386,-25.53234463610459,-25.53355929135987,-25.53334462624224,-25.5339519491163,-25.53373727931224,-25.53434459779167,-25.53555923259499,-25.53677386452289,-25.5363478396656,-25.53635732885224,-25.53635397430913,-25.53877371094048,-25.53855900502262,-25.53916630600211,-25.53895159539869,-25.53955889198267,-25.54077348299008,-25.54198807111534,-25.54155861012536,-25.54277318066676,-25.54398774832349,-25.54355825389402,-25.54477280396559,-25.54598735114995,-25.54558466889372,-25.54566057713563,-25.54563373146824,-25.54677235288162,-25.54798687958979,-25.54756403021597,-25.54758300694679,-25.54757629501684,-25.54877182740994,-25.54998633363806,-25.54955673890664,-25.55077122754563,-25.55198571328987,-25.55155608512996,-25.55277055328375,-25.55255573034243,-25.55316295965952,-25.55294813203535,-25.55476980461938,-25.5543938345635,-25.55454563871072,-25.55449192822085,-25.55555455437573,-25.55676898154761,-25.55633926781,-25.55755367738834,-25.55723137841762,-25.55753497760407,-25.55742754319114,-25.55833833690722,-25.55955272598754,-25.55912296010496,-25.56033733158995,-25.56001499351244,-25.56031858317532,-25.56021113572702,-25.56112190087145,-25.56233625185327,-25.56190643383273,-25.56312076721746,-25.56269428858966,-25.56270377544393,-25.56270041732784,-25.56390524626165,-25.56369031903365,-25.56429747216397,-25.56408254025582,-25.56590398426409,-25.56547409539285,-25.56668837307106,-25.56625846548124,-25.56747272555967,-25.56715028120714,-25.56745384301782,-25.56734636014524,-25.56825704173061,-25.56804206972265,-25.56864918619717,-25.56843420951031,-25.56904132158457,-25.57025554354535,-25.56982556512225,-25.57103976948102,-25.57060977234434,-25.57182395910064,-25.57139394325154,-25.57260811240491,-25.57217807784454,-25.57460637802274,-25.57379999730836,-25.57395176224033,-25.5738980027933,-25.57496035443259,-25.57458402530139,-25.57473578803279,-25.57468202624734,-25.57574436248242,-25.57536801698286,-25.57551977751365,-25.57546601338992,-25.57774241242706,-25.57693589141391,-25.57708764754331,-25.57703387874344,-25.57931021175666,-25.57844984736104,-25.57966385806748,-25.5792336551576,-25.58044764825655,-25.58001742664694,-25.58123140213792,-25.58080116182973,-25.58201511971231,-25.58158486070669,-25.581369729697,-25.5819766965307,-25.58176156084701,-25.58236852327851,-25.58204581236561,-25.58234929055445,-25.58224171883068,-25.5831521495459,-25.58272184913223,-25.58393573950953,-25.58350542040267,-25.58471929317013,-25.58407378496643,-25.58468070924248,-25.58446553416506,-25.58628629158498,-25.58542553721337,-25.58663934247246,-25.5862089445926,-25.58599374414865,-25.58660063467043,-25.58638542955488,-25.58699231567387,-25.58656189509755,-25.58777565045791,-25.58734521119682,-25.58712999006325,-25.58773685563564,-25.58752162983124,-25.5881284910007,-25.58769802904889,-25.58891173450988,-25.58848125387637,-25.58815839077277,-25.58846181025863,-25.5883541878063,-25.58926444241102,-25.58883393909253,-25.59004759465353,-25.58961707265641,-25.58918654665679,-25.59040016993,-25.58996962525365,-25.58959289538009,-25.5897445946432,-25.58969077561053,-25.59075266756209,-25.59032210021035,-25.58999917207238,-25.59030256293933,-25.59019491880971,-25.5911050875574,-25.59067449753412,-25.59045920102363,-25.59106596826438,-25.59085066708602,-25.59145742992354,-25.59102681723254,-25.59081150938892,-25.59141826048564,-25.59120294797462,-25.59180969466811,-25.59137905931323,-25.59105608017668,-25.5913594468276,-25.59125178569917,-25.59216188179871,-25.59173122378378,-25.5913005617779,-25.59251399132294,-25.5920833106518,-25.59143728216602,-25.59204397749273,-25.59182862900136,-25.59243531992489,-25.59200461261427,-25.59157390131771,-25.59278725161066,-25.59152197102498,-25.59159780262636,-25.59157088133211,-25.59270835311667,-25.59227759653456,-25.59184683597153,-25.59141607142874,-25.59262932779252,-25.59176775741841,-25.59112156919858,-25.59172817059531,-25.59151276886501,-25.59211936585892,-25.59168855207887,-25.59125773432524,-25.5908269125992,-25.59044994033122,-25.59060158235555,-25.5905477286969,-25.59160921997893,-25.59074752731807,-25.5892395269737,-25.58984605204586,-25.58963061579001,-25.59023713645991,-25.58980625363565,-25.58937536684866,-25.5889444761001,-25.58851358139114,-25.58808268272295,-25.58765178009669,-25.58722087351353,-25.58678996297464,-25.58635904848117,-25.58592813003431,-25.58549720763521,-25.58506628128503,-25.58463535098495,-25.58420441673612,-25.58377347853973,-25.58334253639692,-25.58291159030887,-25.58248064027674,-25.5820496863017,-25.58161872838491,-25.580405979992,-25.57868216768613,-25.57825120476797,-25.57703852691235,-25.57660757475094,-25.57617661865676,-25.57574565863098,-25.57513934065133,-25.57492386283765,-25.57431754780553,-25.57367111949084,-25.57324016237117,-25.5721791414634,-25.57212527315459,-25.57197369878763,-25.57159662051578,-25.57116567023977,-25.57073471603996,-25.56952216172652,-25.56866027095494,-25.56744774314376,-25.56701680657636,-25.56658586609063,-25.56537336478822,-25.56494243508577,-25.56403306823973,-25.56392533795878,-25.56362221623489,-25.56329902668061,-25.56286810385021,-25.5616556408816,-25.56122472884164,-25.56031539075184,-25.56020766488771,-25.55990455275014,-25.55958137644847,-25.55897515714793,-25.55875970873469,-25.55815349239115,-25.55793804667718,-25.55750715231829,-25.55629473953422,-25.55586385597569,-25.55465145502607,-25.55422058227068,-25.55300819315918,-25.55257733120972,-25.55136495394002,-25.55093410279927,-25.54972173737504,-25.54929089704579,-25.54807854347071,-25.54764771395574,-25.54643537223349,-25.54582920030016,-25.54561379511706,-25.54500762614808,-25.54479222366983,-25.54359883366836,-25.54359210255157,-25.54357315983442,-25.54314909778621,-25.54193677692663,-25.54150599458907,-25.53908137375266,-25.53865061696161,-25.53743831699091,-25.53652909014527,-25.53642140678012,-25.53611833172943,-25.53579528293592,-25.53367377192973,-25.5335660949539,-25.53326302216296,-25.53293999253854,-25.53172771064375,-25.53051542591144,-25.53008474579599,-25.52766019727967,-25.52705405838024,-25.52683873527529,-25.52623259935033,-25.52601727895692,-25.52480501234977,-25.52359274291499,-25.52298660713776,-25.52277130418689,-25.52216517138628,-25.52194987114825,-25.51952534762099,-25.5174038802804,-25.51729624361053,-25.51699317706401,-25.51667026836315,-25.51545801146897,-25.51424575176036,-25.51303348923897,-25.51182122390647,-25.51060895576452,-25.50939668481477,-25.50848747976083,-25.50837986791391,-25.50807680013329,-25.50775396590392,-25.50654170408559,-25.5041171720445,-25.50169262880858,-25.49926807439106,-25.49684350880522,-25.49441893206431,-25.49484879481619,-25.49484761092371,-25.49484803112,-25.49363690771213,-25.49242459762717,-25.49121228475926,-25.48999996911007,-25.48878765068124,-25.48757532947445,-25.48636300549135,-25.48515067873359,-25.48558083978566,-25.48073144600868,-25.47951909064237,-25.47994917403623,-25.47873680114386,-25.47752442548683,-25.47631204706681,-25.47652706517225,-25.47592087123601,-25.47613588468436,-25.47431728766284,-25.47189248197919,-25.47232245430352,-25.47111003256224,-25.4698976080663,-25.46868518081736,-25.46911510497825,-25.46790266021061,-25.46669021269248,-25.46690515855575,-25.46629893007366,-25.46651387127838,-25.46590763841703,-25.46469517063353,-25.46348270010371,-25.46391254269043,-25.46148756385656,-25.46189051007531,-25.46181472844443,-25.46184159134716,-25.46070486473299,-25.45949235368897,-25.45981468587813,-25.4595115549191,-25.45961899757555,-25.45749706960583,-25.45771194126711,-25.45710567089937,-25.45732053790047,-25.456714263155,-25.45550171161206,-25.45582399367966,-25.45552085259624,-25.45562827854527,-25.45350627971256,-25.4538822460054,-25.45373067272379,-25.45378438172158,-25.45272336593878,-25.45151077391225,-25.45194041601248,-25.44951519421604,-25.44994480289223,-25.44873217312363,-25.44894696862164,-25.44834064902011,-25.44855543985609,-25.44794911587825,-25.44673646587875,-25.44716602247917,-25.44595335497544,-25.44616812443435,-25.44556178596611,-25.44577655076232,-25.44395752018873,-25.44438702470639,-25.44317431947444,-25.44338906289076,-25.44278270555927,-25.44299744431222,-25.44239108260531,-25.44117835715276,-25.44160780958066,-25.44039506662742,-25.44071714231974,-25.440413953385,-25.44052131054107]}]]],null,\"b_graus\",{\"crs\":{\"crsClass\":\"L.CRS.EPSG3857\",\"code\":null,\"proj4def\":null,\"projectedBounds\":null,\"options\":{}},\"pane\":\"polygon\",\"stroke\":true,\"color\":\"#333333\",\"weight\":0.5,\"opacity\":0.9,\"fill\":true,\"fillColor\":\"#1A5B8A\",\"fillOpacity\":0.6,\"smoothFactor\":1,\"noClip\":false},\"<div class='scrollableContainer'><table class=mapview-popup id='popup'><tr class='coord'><td><\\/td><th><b>Feature ID&emsp;<\\/b><\\/th><td>1&emsp;<\\/td><\\/tr><tr><td>1<\\/td><th>nome&emsp;<\\/th><td>Paranaguá&emsp;<\\/td><\\/tr><tr><td>2<\\/td><th>geometry&emsp;<\\/th><td>sfc_POLYGON&emsp;<\\/td><\\/tr><\\/table><\\/div>\",{\"maxWidth\":800,\"minWidth\":50,\"autoPan\":true,\"keepInView\":false,\"closeButton\":true,\"closeOnClick\":true,\"className\":\"\"},\"Paranaguá\",{\"interactive\":false,\"permanent\":false,\"direction\":\"auto\",\"opacity\":1,\"offset\":[0,0],\"textsize\":\"10px\",\"textOnly\":false,\"className\":\"\",\"sticky\":true},{\"stroke\":true,\"weight\":1,\"opacity\":0.9,\"fillOpacity\":0.84,\"bringToFront\":false,\"sendToBack\":false}]},{\"method\":\"addScaleBar\",\"args\":[{\"maxWidth\":100,\"metric\":true,\"imperial\":true,\"updateWhenIdle\":true,\"position\":\"bottomleft\"}]},{\"method\":\"addHomeButton\",\"args\":[-48.61257953609523,-25.59278725161066,-48.41129649022949,-25.41032429213982,true,\"b_graus\",\"Zoom to b_graus\",\"<strong> b_graus <\\/strong>\",\"bottomright\"]},{\"method\":\"addLegend\",\"args\":[{\"colors\":[\"#1A5B8A\"],\"labels\":[\"Paranaguá\"],\"na_color\":null,\"na_label\":\"NA\",\"opacity\":1,\"position\":\"topright\",\"type\":\"factor\",\"title\":\"\",\"extra\":null,\"layerId\":null,\"className\":\"info legend\",\"group\":\"b_graus\"}]},{\"method\":\"addPolygons\",\"args\":[[[[{\"lng\":[-48.41249247409851,-48.41252748109794,-48.41283485536348,-48.4134137865111,-48.41426271956841,-48.41537935888702,-48.41676067409157,-48.41840290805258,-48.4203015868653,-48.42245153181049,-48.4248468732679,-48.42748106654734,-48.43034690959685,-48.43343656254202,-48.43674156900527,-48.44025287914842,-48.44396087437708,-48.44785539364018,-48.45192576125356,-48.45616081617129,-48.46054894262492,-48.46507810204576,-48.46973586618203,-48.4745094513188,-48.47938575350504,-48.48435138468943,-48.48939270966325,-48.49449588370636,-48.49964689083034,-48.50483158251016,-48.51003571679532,-48.51524499768902,-48.52044511468402,-48.52562178234263,-48.53076077980857,-48.53584799013819,-48.54086943933968,-48.54581133500894,-48.55066010445301,-48.55540243219252,-48.56002529673751,-48.56451600653227,-48.56886223496828,-48.57305205436651,-48.57707396883396,-48.58091694590242,-48.58457044686166,-48.58802445570245,-48.59126950658992,-48.59429670979161,-48.5970977759892,-48.59966503890839,-48.60199147620551,-48.60407072855531,-48.60589711688939,-48.60746565774015,-48.60877207665073,-48.60981281961698,-48.61058506253318,-48.61108671861878,-48.61131644380954,-48.61127364010157,-48.61095845684324,-48.61037178997489,-48.60951527922247,-48.60839130325659,-48.60700297283402,-48.60535412194404,-48.60344929698764,-48.60129374402239,-48.59889339411117,-48.59625484681803,-48.59338535189875,-48.59029278923876,-48.58698564709561,-48.58347299870703,-48.57976447733017,-48.57587024978131,-48.57180098854922,-48.5675678425587,-48.56318240666415,-48.55865668995641,-48.55400308296853,-48.54923432386911,-48.54436346373421,-48.53940383099085,-48.53436899512743,-48.5292727297677,-48.52412897520675,-48.51895180050843,-48.51375536526507,-48.5085538811205,-48.50336157315847,-48.49819264125861,-48.49306122152203,-48.48798134786857,-48.48296691390745,-48.47803163518194,-48.47318901188817,-48.46845229216684,-48.46383443606536,-48.45934808026604,-48.45500550367442,-48.45081859395957,-48.44679881513592,-48.44295717627367,-48.43930420142206,-48.43584990082685,-48.43260374352003,-48.42957463135692,-48.42677087457134,-48.42420016891671,-48.42186957445639,-48.41978549606264,-48.41795366567911,-48.41637912639762,-48.41506621839488,-48.41401856677063,-48.41323907132286,-48.41272989829186,-48.41249247409851],\"lat\":[-25.49987851865104,-25.50460227114645,-25.50931788558118,-25.51401243756966,-25.51867305893489,-25.52328697298583,-25.52784152956069,-25.53232423973985,-25.53672281013299,-25.54102517664568,-25.54521953763235,-25.54929438634356,-25.55323854257785,-25.55704118344996,-25.56069187318985,-25.56418059188924,-25.56749776311561,-25.57063428031574,-25.57358153193545,-25.57633142518407,-25.57887640837757,-25.58120949179658,-25.58332426700076,-25.58521492454473,-25.58687627004529,-25.5883037385543,-25.58949340719624,-25.59044200603446,-25.59114692713515,-25.59160623180281,-25.59181865596669,-25.59178361370228,-25.59150119887802,-25.59097218492176,-25.5901980227078,-25.58918083656994,-25.58792341845162,-25.58642922020977,-25.58470234409345,-25.58274753142475,-25.58057014951311,-25.57817617684051,-25.57557218655901,-25.57276532834726,-25.56976330867716,-25.56657436954628,-25.5632072657359,-25.55967124065883,-25.55597600086476,-25.55213168927495,-25.54814885722141,-25.54403843536873,-25.53981170360036,-25.53548025995332,-25.53105598868814,-25.52655102758316,-25.52197773454425,-25.51734865362268,-25.51267648053555,-25.50797402778447,-25.50325418946855,-25.49852990588936,-25.49381412804506,-25.48911978211164,-25.48445973400857,-25.47984675414623,-25.47529348245141,-25.4708123937665,-25.46641576371663,-25.46211563513763,-25.45792378515607,-25.45385169301051,-25.44991050870111,-25.4461110225523,-25.44246363577049,-25.43897833207614,-25.43566465048638,-25.43253165932123,-25.42958793150288,-25.42684152121443,-25.42429994197972,-25.42197014622351,-25.4198585063656,-25.41797079749966,-25.41631218170228,-25.41488719401422,-25.41369973013034,-25.41275303583127,-25.41204969818412,-25.41159163853556,-25.41138010731555,-25.41141568066524,-25.41169825889749,-25.41222706679413,-25.41300065573857,-25.41401690767802,-25.41527304090442,-25.41676561763865,-25.41849055339736,-25.42044312811773,-25.42261799900995,-25.42500921510355,-25.42761023344833,-25.43041393692702,-25.43341265363176,-25.43659817775311,-25.43996179192538,-25.44349429096905,-25.44718600696633,-25.45102683560332,-25.45500626370789,-25.45911339790964,-25.46333699434513,-25.46766548932847,-25.47208703090509,-25.47658951120345,-25.48116059949766,-25.48578777589191,-25.49045836553525,-25.49515957327451,-25.49987851865104]}]]],null,\"b_metros\",{\"crs\":{\"crsClass\":\"L.CRS.EPSG3857\",\"code\":null,\"proj4def\":null,\"projectedBounds\":null,\"options\":{}},\"pane\":\"polygon\",\"stroke\":true,\"color\":\"#333333\",\"weight\":0.5,\"opacity\":0.9,\"fill\":true,\"fillColor\":\"#B3402A\",\"fillOpacity\":0.6,\"smoothFactor\":1,\"noClip\":false},\"<div class='scrollableContainer'><table class=mapview-popup id='popup'><tr class='coord'><td><\\/td><th><b>Feature ID&emsp;<\\/b><\\/th><td>1&emsp;<\\/td><\\/tr><tr><td>1<\\/td><th>nome&emsp;<\\/th><td>Paranaguá&emsp;<\\/td><\\/tr><tr><td>2<\\/td><th>geometry&emsp;<\\/th><td>sfc_POLYGON&emsp;<\\/td><\\/tr><\\/table><\\/div>\",{\"maxWidth\":800,\"minWidth\":50,\"autoPan\":true,\"keepInView\":false,\"closeButton\":true,\"closeOnClick\":true,\"className\":\"\"},\"Paranaguá\",{\"interactive\":false,\"permanent\":false,\"direction\":\"auto\",\"opacity\":1,\"offset\":[0,0],\"textsize\":\"10px\",\"textOnly\":false,\"className\":\"\",\"sticky\":true},{\"stroke\":true,\"weight\":1,\"opacity\":0.9,\"fillOpacity\":0.84,\"bringToFront\":false,\"sendToBack\":false}]},{\"method\":\"addHomeButton\",\"args\":[-48.61131644380954,-25.59181865596669,-48.41249247409851,-25.41138010731555,true,\"b_metros\",\"Zoom to b_metros\",\"<strong> b_metros <\\/strong>\",\"bottomright\"]},{\"method\":\"addLayersControl\",\"args\":[[\"CartoDB.Positron\",\"CartoDB.DarkMatter\",\"OpenStreetMap\",\"Esri.WorldImagery\",\"OpenTopoMap\"],[\"b_graus\",\"b_metros\"],{\"collapsed\":true,\"autoZIndex\":true,\"position\":\"topleft\"}]},{\"method\":\"addLegend\",\"args\":[{\"colors\":[\"#B3402A\"],\"labels\":[\"Paranaguá\"],\"na_color\":null,\"na_label\":\"NA\",\"opacity\":1,\"position\":\"topright\",\"type\":\"factor\",\"title\":\"\",\"extra\":null,\"layerId\":null,\"className\":\"info legend\",\"group\":\"b_metros\"}]},{\"method\":\"addHomeButton\",\"args\":[-48.61257953609523,-25.59278725161066,-48.41129649022949,-25.41032429213982,true,null,\"Zoom to full extent\",\"<strong>Zoom full<\\/strong>\",\"bottomleft\"]}],\"limits\":{\"lat\":[-25.59278725161066,-25.41032429213982],\"lng\":[-48.61257953609523,-48.41129649022949]},\"fitBounds\":[-25.59278725161066,-48.61257953609523,-25.41032429213982,-48.41129649022949,[]]},\"evals\":[],\"jsHooks\":{\"render\":[{\"code\":\"function(el, x, data) {\\n  return (\\n      function(el, x, data) {\\n      // get the leaflet map\\n      var map = this; //HTMLWidgets.find('#' + el.id);\\n      // we need a new div element because we have to handle\\n      // the mouseover output separately\\n      // debugger;\\n      function addElement () {\\n      // generate new div Element\\n      var newDiv = $(document.createElement('div'));\\n      // append at end of leaflet htmlwidget container\\n      $(el).append(newDiv);\\n      //provide ID and style\\n      newDiv.addClass('lnlt');\\n      newDiv.css({\\\"position\\\":\\\"relative\\\",\\\"bottomleft\\\":\\\"0px\\\",\\\"background-color\\\":\\\"rgba(255, 255, 255, 0.7)\\\",\\\"box-shadow\\\":\\\"0 0 2px #bbb\\\",\\\"background-clip\\\":\\\"padding-box\\\",\\\"margin\\\":\\\"0\\\",\\\"padding-left\\\":\\\"5px\\\",\\\"padding-right\\\":\\\"5px\\\",\\\"color\\\":\\\"#333\\\",\\\"font-size\\\":\\\"9px\\\",\\\"font-family\\\":\\\"\\\\\\\"Helvetica Neue\\\\\\\", Arial, Helvetica, sans-serif\\\",\\\"text-align\\\":\\\"left\\\",\\\"z-index\\\":\\\"700\\\"});\\n      return newDiv;\\n      }\\n\\n\\n      // check for already existing lnlt class to not duplicate\\n      var lnlt = $(el).find('.lnlt');\\n\\n      if(!lnlt.length) {\\n      lnlt = addElement();\\n\\n      // grab the special div we generated in the beginning\\n      // and put the mousmove output there\\n\\n      map.on('mousemove', function (e) {\\n      if (e.originalEvent.ctrlKey) {\\n      if (document.querySelector('.lnlt') === null) lnlt = addElement();\\n      lnlt.text(\\n                           ' lon: ' + (e.latlng.lng).toFixed(5) +\\n                           ' | lat: ' + (e.latlng.lat).toFixed(5) +\\n                           ' | zoom: ' + map.getZoom() +\\n                           ' | x: ' + L.CRS.EPSG3857.project(e.latlng).x.toFixed(0) +\\n                           ' | y: ' + L.CRS.EPSG3857.project(e.latlng).y.toFixed(0) +\\n                           ' | epsg: 3857 ' +\\n                           ' | proj4: +proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +no_defs ');\\n      } else {\\n      if (document.querySelector('.lnlt') === null) lnlt = addElement();\\n      lnlt.text(\\n                      ' lon: ' + (e.latlng.lng).toFixed(5) +\\n                      ' | lat: ' + (e.latlng.lat).toFixed(5) +\\n                      ' | zoom: ' + map.getZoom() + ' ');\\n      }\\n      });\\n\\n      // remove the lnlt div when mouse leaves map\\n      map.on('mouseout', function (e) {\\n      var strip = document.querySelector('.lnlt');\\n      if( strip !==null) strip.remove();\\n      });\\n\\n      };\\n\\n      //$(el).keypress(67, function(e) {\\n      map.on('preclick', function(e) {\\n      if (e.originalEvent.ctrlKey) {\\n      if (document.querySelector('.lnlt') === null) lnlt = addElement();\\n      lnlt.text(\\n                      ' lon: ' + (e.latlng.lng).toFixed(5) +\\n                      ' | lat: ' + (e.latlng.lat).toFixed(5) +\\n                      ' | zoom: ' + map.getZoom() + ' ');\\n      var txt = document.querySelector('.lnlt').textContent;\\n      console.log(txt);\\n      //txt.innerText.focus();\\n      //txt.select();\\n      setClipboardText('\\\"' + txt + '\\\"');\\n      }\\n      });\\n\\n      }\\n      ).call(this.getMap(), el, x, data);\\n}\",\"data\":null},{\"code\":\"function(el, x, data) {\\n  return (function(el,x,data){\\n           var map = this;\\n\\n           map.on('keypress', function(e) {\\n               console.log(e.originalEvent.code);\\n               var key = e.originalEvent.code;\\n               if (key === 'KeyE') {\\n                   var bb = this.getBounds();\\n                   var txt = JSON.stringify(bb);\\n                   console.log(txt);\\n\\n                   setClipboardText('\\\\'' + txt + '\\\\'');\\n               }\\n           })\\n        }).call(this.getMap(), el, x, data);\\n}\",\"data\":null}]}}</script>\n```\n\n:::\n:::\n\n\nO problema clássico aparece quando o `s2` está desligado, em versões antigas do `sf` e em\nvários outros programas: o raio é interpretado **em graus**, gerando um \"buffer\" de milhares\nde quilômetros.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsf::sf_use_s2(FALSE)\nb_errado <- suppressWarnings(sf::st_buffer(portos[1, ], dist = 10000))\nsf::st_bbox(b_errado)          # o retângulo envolvente extrapola o planeta\n#>       xmin       ymin       xmax       ymax \n#> -10048.512 -10025.502   9951.488   9974.498\nsf::sf_use_s2(TRUE)            # religue sempre\n```\n:::\n\n\nPor isso a recomendação para trabalho métrico continua a mesma: **reprojete para UTM, faça as\noperações, e volte para 4674 ao gravar o resultado**. Assim o código funciona igual em\nqualquer versão e é auditável por quem abrir no QGIS.\n\nA regra prática:\n\n| Operação | Precisa reprojetar? |\n|:--|:--|\n| `st_distance()` | não (o `s2` resolve em graus) |\n| `st_buffer()` | **sim**: o raio é na unidade do CRS |\n| `st_area()`, `st_length()` | não para valores globais, **sim** para precisão local |\n| `st_intersection()`, `st_join()` | não, mas as camadas devem estar no **mesmo** CRS |\n| grades regulares, *snapping*, roteamento | **sim** |\n\n## Camadas em CRS diferentes\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# duas camadas em sistemas diferentes: a operação falha (e é bom que falhe)\nsf::st_intersects(portos, sf::st_transform(portos, 31982))\n#> Error in `st_geos_binop()`:\n#> ! st_crs(x) == st_crs(y) is not TRUE\n```\n:::\n\n\nO padrão para alinhar tudo a um CRS de trabalho:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrs_trabalho <- 31982\n\ncamadas <- list(rodovias = rodovias, setores = setores, portos = portos)\ncamadas <- lapply(camadas, st_transform, crs = crs_trabalho)\n```\n:::\n\n\nUma função útil para descobrir a zona UTM certa a partir do próprio dado:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nzona_utm <- function(x) {\n  centro <- suppressWarnings(sf::st_centroid(sf::st_as_sfc(sf::st_bbox(sf::st_transform(x, 4326)))))\n  lon <- sf::st_coordinates(centro)[1]\n  lat <- sf::st_coordinates(centro)[2]\n  zona <- floor((lon + 180) / 6) + 1\n  # SIRGAS 2000 / UTM: 31978+zona-17 no hemisfério sul (zonas 18S a 25S)\n  epsg <- if (lat < 0) 31960 + zona else 31954 + zona\n  epsg\n}\n\nzona_utm(portos)          # PR/SC -> 31982 (UTM 22S)\n#> [1] 31982\n```\n:::\n\n\nPara mapas e cálculos no Brasil inteiro, a projeção de áreas iguais usada pelo IBGE e pelo\nIpea:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrs_brasil <- paste(\"+proj=aea +lat_0=-12 +lon_0=-54 +lat_1=-2 +lat_2=-22\",\n                    \"+x_0=0 +y_0=0 +ellps=GRS80 +units=m +no_defs\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\narquivo <- \"dados/brutos/pr.gpkg\"\nif (!file.exists(arquivo)) {\n  pr <- geobr::read_state(code_state = \"PR\", year = 2020, showProgress = FALSE)\n  sf::st_write(pr, arquivo, quiet = TRUE)\n}\npr <- sf::st_read(arquivo, quiet = TRUE)\n\nmapa <- function(x, titulo) {\n  ggplot(x) + geom_sf(fill = \"#d7e3ee\", colour = \"#1a5b8a\", linewidth = 0.3) +\n    labs(title = titulo) + theme_void(base_size = 9) +\n    theme(plot.title = element_text(hjust = 0.5))\n}\n\npatchwork::wrap_plots(\n  mapa(sf::st_transform(pr, 4674),       \"SIRGAS 2000 (graus)\"),\n  mapa(sf::st_transform(pr, 31982),      \"UTM 22S (metros)\"),\n  mapa(sf::st_transform(pr, crs_brasil), \"Albers Brasil\"),\n  nrow = 1\n)\n```\n\n::: {.cell-output-display}\n![A mesma UF em três projeções: geográfica, UTM 22S e Albers do Brasil](m2-02-crs_files/figure-html/fig-crs-comparacao-1.png){#fig-crs-comparacao width=1200}\n:::\n:::\n\n\nAs três são a mesma geometria. A diferença de forma é a distorção de cada projeção. E é por\nisso que a escolha importa quando o resultado vai ser medido, não apenas olhado.\n",
    "supporting": [
      "m2-02-crs_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/htmltools-fill-0.5.9/fill.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<script src=\"site_libs/jquery-3.6.0/jquery-3.6.0.min.js\"></script>\n<link href=\"site_libs/leaflet-1.3.1/leaflet.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/leaflet-1.3.1/leaflet.js\"></script>\n<link href=\"site_libs/leafletfix-1.0.0/leafletfix.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/proj4-2.6.2/proj4.min.js\"></script>\n<script src=\"site_libs/Proj4Leaflet-1.0.1/proj4leaflet.js\"></script>\n<link href=\"site_libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/leaflet-binding-2.2.3/leaflet.js\"></script>\n<script src=\"site_libs/leaflet-providers-3.0.0/leaflet-providers.js\"></script>\n<script src=\"site_libs/leaflet-providers-plugin-2.2.3/leaflet-providers-plugin.js\"></script>\n<script src=\"site_libs/HomeButton-0.0.1/home-button.js\"></script>\n<script src=\"site_libs/HomeButton-0.0.1/easy-button-src.min.js\"></script>\n<link href=\"site_libs/b_graus-CSS-0.0.1/b_graus_home-button.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/clipboard-0.0.1/setClipboardText.js\"></script>\n<link href=\"site_libs/mapviewCSS-0.0.1/mapview-popup.css\" rel=\"stylesheet\" />\n<link href=\"site_libs/mapviewCSS-0.0.1/mapview.css\" rel=\"stylesheet\" />\n<link href=\"site_libs/b_metros-CSS-0.0.1/b_metros_home-button.css\" rel=\"stylesheet\" />\n<link href=\"site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}