{
  "hash": "f7dde2cd10d7d974d5f1884bdd84d2f2",
  "result": {
    "engine": "knitr",
    "markdown": "# Estudo de caso: a saída de um modelo quatro etapas {#sec-m1-modelo4etapas}\n\n::: {.modulo-meta}\n**Dados:** `dados/processados/modelo4etapas/links_rmc_2018_completo.parquet`\n**Origem:** exportação PTV VISUM, hora pico manhã, Região Metropolitana de Curitiba (rede de\n2018, contagens de 2017)\n**Fio condutor:** este mesmo dado reaparece nos módulos 2 a 5\n:::\n\nOs capítulos anteriores trabalharam com uma base pública já tabulada. Este trabalha com o\noutro tipo de arquivo que chega à mesa de quem planeja transporte: a **exportação de um\nmodelo de simulação**. O R aqui não é a ferramenta de modelagem, é a ferramenta de\npós-processamento, que é como a maioria das equipes técnicas efetivamente usa a linguagem.\n\nA pergunta é a de uma nota técnica qualquer:\n\n> *Quanto a rede roda, quanto ela perde em congestionamento, e onde estão os gargalos?*\n\nParece uma soma. Vamos ver que não é.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(ggplot2)\nlibrary(scales)\n\nggplot2::theme_set(\n  ggplot2::theme_minimal(base_size = 11) +\n    ggplot2::theme(panel.grid.minor = ggplot2::element_blank(),\n                   plot.title = ggplot2::element_text(face = \"bold\"),\n                   legend.position = \"bottom\")\n)\n```\n:::\n\n\n## Passo 1: Ler o arquivo\n\nO recorte está em Parquet, formato colunar que ocupa uma fração do shapefile original e é\nlido em uma fração do tempo (SQL com DuckDB, no Módulo 3). Leitura direta pelo DuckDB, sem carregar nada\nque não seja necessário:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncon <- duckdb::dbConnect(duckdb::duckdb())\n\nlinks <- DBI::dbGetQuery(con, \"\n  SELECT *\n  FROM 'dados/processados/modelo4etapas/links_rmc_2018_completo.parquet'\n\")\n\nduckdb::dbDisconnect(con, shutdown = TRUE)\n\ndim(links)\n#> [1] 208336     36\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlinks |>\n  dplyr::select(no, name, sentido, typeno, numlanes, capprt, v0prt, volvehprt, vc) |>\n  dplyr::slice_head(n = 5) |>\n  knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n| no|name                       |sentido | typeno| numlanes| capprt| v0prt| volvehprt|   vc|\n|--:|:--------------------------|:-------|------:|--------:|------:|-----:|---------:|----:|\n|  2|Rodoanel Contorno Leste    |direto  |     11|        2|   3000|   110|      2179| 0.73|\n|  2|Rodoanel Contorno Leste    |inverso |     11|        2|   3000|   110|         0| 0.00|\n|  8|Rua General Mário Tourinho |direto  |     32|        3|   3900|    50|         0| 0.00|\n|  8|Rua General Mário Tourinho |inverso |     32|        3|   3900|    50|      1557| 0.40|\n|  9|Rua General Mário Tourinho |direto  |     32|        3|   3900|    50|      1481| 0.38|\n\n\n:::\n:::\n\n\n## Passo 2: Três perguntas antes de qualquer conta\n\n**1. Qual é a unidade de observação?** A tentação é dizer \"um link\". Está errado:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(\n  linhas        = nrow(links),\n  links_unicos  = dplyr::n_distinct(links$no),\n  link_sentido  = nrow(dplyr::distinct(links, no, sentido))\n)\n#>       linhas links_unicos link_sentido \n#>       208336       104168       208336\n```\n:::\n\n\nCada link físico aparece **duas vezes**, uma por sentido. A chave é `no` + `sentido`.\nAgrupar por `no` sem perceber isso mistura os dois sentidos de cada via.\n\n::: {.callout-warning}\n## A mesma rede, duas convenções\n\nA exportação original traz a mesma rede em **dois formatos diferentes**: um arquivo com uma\nlinha por sentido (o que estamos usando) e outro com ida e volta na **mesma linha**, em\ncolunas prefixadas por `R_`. É o caso clássico de formato longo contra formato largo\n(@sec-m1-manipulacao). Somar as duas exportações juntas conta tudo duas vezes.\n:::\n\n**2. O dado cobre o que se espera?**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlinks |>\n  dplyr::summarise(\n    tipos_de_via   = dplyr::n_distinct(typeno),\n    extensao_km    = round(sum(comprimento_km, na.rm = TRUE)),\n    com_volume     = sum(volvehprt > 0, na.rm = TRUE),\n    com_contagem   = sum(tem_contagem, na.rm = TRUE),\n    postos         = dplyr::n_distinct(id_posto[tem_contagem])\n  ) |>\n  knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n| tipos_de_via| extensao_km| com_volume| com_contagem| postos|\n|------------:|-----------:|----------:|------------:|------:|\n|           37|       28257|      79680|           63|     26|\n\n\n:::\n:::\n\n\nVinte e cinco postos de contagem para uma rede de 28 mil quilômetros. É pouco, e é o que\nexiste. Saber disso antes de prometer uma validação é parte do trabalho.\n\n**3. Há valores impossíveis ou sentinelas?**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(\n  sem_acesso      = sum(links$sem_acesso, na.rm = TRUE),\n  tsys_vazio      = sum(is.na(links$tsysset) | links$tsysset == \"\"),\n  capacidade_zero = sum(links$capprt == 0, na.rm = TRUE)\n)\n#>      sem_acesso      tsys_vazio capacidade_zero \n#>           23290           13693            2871\n```\n:::\n\n\nOs 23.290 links marcados como `sem_acesso` traziam, no arquivo original, tempo de percurso\nigual a **360.000.000**. Não é um tempo: é o sentinela que o VISUM usa para dizer \"este\nsistema de transporte não pode usar este link\". Quem calcula um tempo médio sem tratar esse\nvalor obtém um número sem sentido, e o R não reclama.\n\n## Passo 3: A armadilha das unidades\n\nEsta é a parte que justifica o capítulo. O VISUM exporta campos cujo **nome não corresponde\nà unidade gravada**. Veja o primeiro link do Contorno Leste:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlinks |>\n  dplyr::filter(no == 2, sentido == \"direto\") |>\n  dplyr::transmute(\n    name,\n    volume          = volvehprt,\n    comprimento_km,\n    campo_VEHKMTRAVPRT = vehkmtravprt,\n    conferencia     = volvehprt * comprimento_km\n  ) |>\n  knitr::kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|name                    | volume| comprimento_km| campo_VEHKMTRAVPRT| conferencia|\n|:-----------------------|------:|--------------:|------------------:|-----------:|\n|Rodoanel Contorno Leste |   2179|          0.135|           294289.8|     294.243|\n\n\n:::\n:::\n\n\nO campo se chama `VEHKMTRAVPRT`, \"veículos-quilômetro percorridos\". Deveria valer\n2.179 × 0,135 = **294**. Vale **294.290**. Está em **metros**, não em quilômetros.\n\nO mesmo vale para o tempo: `VEHHOURTRAVTCUR`, \"veículos-hora\", está em **segundos**. E\n`VOLCAPRATIOPRT` está em **percentual**, não em razão.\n\nO recorte já traz as colunas corrigidas (`veic_km`, `veic_h_livre`, `veic_h_carreg`, `vc`),\nmas o hábito que interessa é o da conferência: **recalcule o indicador por um caminho\nindependente e veja se bate.**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlinks |>\n  dplyr::summarise(\n    soma_do_campo = sum(veic_km, na.rm = TRUE),\n    recalculado   = sum(volvehprt * comprimento_km, na.rm = TRUE),\n    diferenca_pct = round(100 * (recalculado / soma_do_campo - 1), 3)\n  ) |>\n  knitr::kable(digits = 3, format.args = list(big.mark = \".\"))\n```\n\n::: {.cell-output-display}\n\n\n| soma_do_campo| recalculado| diferenca_pct|\n|-------------:|-----------:|-------------:|\n|     3.676.335|   3.589.250|        -2.369|\n\n\n:::\n:::\n\n\n::: {.callout-important}\n## O erro que não dá erro\n\nSe você somar `VEHKMTRAVPRT` acreditando no nome, obtém 3,7 **bilhões** de veículos-quilômetro\nnuma região metropolitana de 3 milhões de habitantes. O código roda, o gráfico sai bonito, e\no número está mil vezes errado. Nenhuma mensagem de aviso aparece. A única defesa é a\nconferência por um caminho independente.\n:::\n\n## Passo 4: Os totais da rede\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntotais <- links |>\n  dplyr::summarise(\n    veic_km         = sum(veic_km, na.rm = TRUE),\n    veic_h_livre    = sum(veic_h_livre, na.rm = TRUE),\n    veic_h_carreg   = sum(veic_h_carreg, na.rm = TRUE),\n    atraso_veic_h   = sum(atraso_veic_h, na.rm = TRUE),\n    vel_media_kmh   = sum(veic_km, na.rm = TRUE) / sum(veic_h_carreg, na.rm = TRUE),\n    vel_livre_kmh   = sum(veic_km, na.rm = TRUE) / sum(veic_h_livre, na.rm = TRUE),\n    links_saturados = sum(vc >= 1, na.rm = TRUE)\n  )\n\ntotais |>\n  dplyr::mutate(dplyr::across(dplyr::everything(), ~ round(.x, 1))) |>\n  knitr::kable(format.args = list(big.mark = \".\"))\n```\n\n::: {.cell-output-display}\n\n\n|   veic_km| veic_h_livre| veic_h_carreg| atraso_veic_h| vel_media_kmh| vel_livre_kmh| links_saturados|\n|---------:|------------:|-------------:|-------------:|-------------:|-------------:|---------------:|\n| 3.676.335|       67.755|       176.158|       108.403|          20.9|          54.3|           3.436|\n\n\n:::\n:::\n\n\nGuarde estes números: **3.676.335 veículos-quilômetro** e **108.403 veículos-hora de atraso**\nna hora pico. Depois de qualquer filtro ou `join`, confira contra eles. É o mesmo princípio\nde @sec-m1-joins: o total conhecido é a sua âncora.\n\n## Passo 5: Onde está o atraso (e por que o total engana)\n\nAgora a pergunta que a nota técnica realmente faz. Vamos classificar as vias pela dezena do\ncódigo de tipo do modelo:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclasses <- links |>\n  dplyr::mutate(\n    classe = dplyr::case_when(\n      typeno %/% 10 == 1            ~ \"1. Rodovia e via expressa\",\n      typeno %/% 10 %in% c(2, 3)    ~ \"2. Arterial\",\n      typeno %/% 10 == 4            ~ \"3. Coletora\",\n      typeno %/% 10 %in% c(5, 6)    ~ \"4. Local\",\n      typeno %/% 10 == 7            ~ \"5. Acesso local e conector\",\n      .default                      = \"6. Sem carregamento\"\n    )\n  ) |>\n  dplyr::summarise(\n    links       = dplyr::n(),\n    extensao_km = sum(comprimento_km, na.rm = TRUE),\n    veic_km     = sum(veic_km, na.rm = TRUE),\n    atraso_h    = sum(atraso_veic_h, na.rm = TRUE),\n    .by = classe\n  ) |>\n  dplyr::mutate(\n    pct_veic_km = 100 * veic_km / sum(veic_km),\n    pct_atraso  = 100 * atraso_h / sum(atraso_h)\n  ) |>\n  dplyr::arrange(classe)\n\nclasses |>\n  knitr::kable(digits = 1, format.args = list(big.mark = \".\"))\n```\n\n::: {.cell-output-display}\n\n\n|classe                     |   links| extensao_km|   veic_km| atraso_h| pct_veic_km| pct_atraso|\n|:--------------------------|-------:|-----------:|---------:|--------:|-----------:|----------:|\n|1. Rodovia e via expressa  |   3.647|     1.205.6| 803.734.4|  2.611.7|        21.9|        2.4|\n|2. Arterial                |  11.628|     1.376.5| 983.410.5|  6.995.4|        26.7|        6.5|\n|3. Coletora                |  17.873|     1.706.0| 674.440.7|  6.035.3|        18.3|        5.6|\n|4. Local                   |  35.446|     9.788.8| 819.989.1| 10.500.4|        22.3|        9.7|\n|5. Acesso local e conector | 136.881|    13.605.6| 394.760.4| 82.260.2|        10.7|       75.9|\n|6. Sem carregamento        |   2.861|       574.9|       0.0|      0.0|         0.0|        0.0|\n\n\n:::\n:::\n\n\nO resultado é desconfortável e é o ponto do capítulo: a categoria **\"acesso local e\nconector\"** responde por cerca de 11% dos veículos-quilômetro e por **76% de todo o atraso da\nrede**. São links de acesso com relação volume/capacidade de 7, 8, 11 vezes.\n\nIsso não é congestionamento real. É **artefato de modelagem**: o conector é a costura por\nonde a demanda da zona entra na rede, e ele não representa uma via com capacidade física.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlinks |>\n  dplyr::filter(!is.na(atraso_veic_h)) |>\n  dplyr::slice_max(atraso_veic_h, n = 8) |>\n  dplyr::transmute(no, name, typeno, volvehprt, vc = round(vc, 1),\n                   atraso_h = round(atraso_veic_h)) |>\n  knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n|     no|name                                 | typeno| volvehprt|   vc| atraso_h|\n|------:|:------------------------------------|------:|---------:|----:|--------:|\n| 124919|NA                                   |     71|      2231| 11.2|    23089|\n|  20424|Rua Edgard Moutinho Zandoná          |     70|      3387|  8.5|    15747|\n|  65913|Rua Maria de Lourdes Grabowski Kampa |     70|      2892|  7.2|     7458|\n| 130806|NA                                   |     71|      1233|  6.2|     3565|\n| 122592|NA                                   |     71|      1513|  7.6|     3117|\n| 122593|NA                                   |     71|      1513|  7.6|     2184|\n|   6202|Rua Alfredo Pinto                    |     50|      2973|  3.7|     1169|\n|  17477|Rua Aquelino Orestes Baglioli        |     60|      3040|  3.8|     1165|\n\n\n:::\n:::\n\n\nRepare que os piores casos não têm nome de via. São exatamente os conectores.\n\n::: {.callout-important}\n## O indicador que você publica muda conforme o que você inclui\n\nReportar \"108 mil horas de atraso na hora pico\" sem qualificar é reportar, em três quartos,\num artefato do modelo. Restringindo à rede real (rodovias, arteriais e coletoras), o atraso\ncai para cerca de **15,6 mil veículos-hora**.\n\nAs duas contas estão \"certas\" no sentido de que o código rodou. Só uma delas você consegue\ndefender numa reunião.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclasses |>\n  tidyr::pivot_longer(c(pct_veic_km, pct_atraso),\n                      names_to = \"indicador\", values_to = \"pct\") |>\n  dplyr::mutate(indicador = dplyr::recode(indicador,\n                                          pct_veic_km = \"Veículos-km\",\n                                          pct_atraso  = \"Atraso\")) |>\n  ggplot2::ggplot(ggplot2::aes(x = pct, y = forcats::fct_rev(classe), fill = indicador)) +\n  ggplot2::geom_col(position = \"dodge\") +\n  ggplot2::scale_x_continuous(labels = scales::label_percent(scale = 1)) +\n  ggplot2::scale_fill_manual(values = c(\"Veículos-km\" = \"#1a5b8a\", \"Atraso\" = \"#c2542d\")) +\n  ggplot2::labs(x = NULL, y = NULL, fill = NULL,\n                title = \"Onde a rede roda e onde a rede perde tempo\",\n                subtitle = \"RMC, hora pico manhã, modelo de 2018\")\n```\n\n::: {.cell-output-display}\n![Participação de cada classe de via nos veículos-quilômetro e no atraso total.](m1-08b-modelo4etapas_files/figure-html/unnamed-chunk-12-1.png){width=1200}\n:::\n:::\n\n\n## Passo 6: O recorte defensável\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrede_real <- links |> dplyr::filter(typeno < 50)\n\nrede_real |>\n  dplyr::summarise(\n    links         = dplyr::n(),\n    extensao_km   = round(sum(comprimento_km, na.rm = TRUE)),\n    veic_km       = round(sum(veic_km, na.rm = TRUE)),\n    atraso_veic_h = round(sum(atraso_veic_h, na.rm = TRUE)),\n    vel_media_kmh = round(sum(veic_km, na.rm = TRUE) / sum(veic_h_carreg, na.rm = TRUE), 1),\n    saturados     = sum(vc >= 1, na.rm = TRUE)\n  ) |>\n  knitr::kable(format.args = list(big.mark = \".\"))\n```\n\n::: {.cell-output-display}\n\n\n|  links| extensao_km|   veic_km| atraso_veic_h| vel_media_kmh| saturados|\n|------:|-----------:|---------:|-------------:|-------------:|---------:|\n| 33.174|       4.290| 2.461.586|        15.642|          45.8|     1.837|\n\n\n:::\n:::\n\n\nVelocidade média de 45,8 km/h na rede estrutural, contra os 20,9 km/h do total. A diferença\ninteira vem de decidir, conscientemente, o que entra na conta. **Essa decisão é a análise.**\n\n## Checklist de conferência\n\nEste é o hábito que o curso quer instalar, e ele reaparece em todos os módulos:\n\n::: {.callout-tip}\n## Antes de publicar qualquer número saído de um modelo\n\n1. **Unidade de observação.** Quantas linhas por objeto físico? Contar `distinct` na chave\n   que você acredita ser única.\n2. **Unidades de medida.** Recalcular pelo menos um indicador por caminho independente e\n   comparar. Nunca confiar no nome do campo.\n3. **Sentinelas.** Procurar valores absurdos (`360000000`, `-1`, `9999`) antes de calcular\n   médias.\n4. **Totais-âncora.** Registrar os totais da base completa e conferir contra eles depois de\n   cada filtro e cada `join`.\n5. **O que entra na conta.** Separar rede real de artefato de modelagem, e declarar essa\n   escolha no relatório.\n:::\n\n## O que vem a seguir\n\nEste mesmo dado atravessa o resto do curso:\n\n| Módulo | O que faremos com ele |\n|:--|:--|\n| @sec-m2 | Ler a camada espacial, reprojetar, conferir o comprimento calculado contra o gravado, mapear carregamento e saturação |\n| Módulo 3 | Comparar o modelo com as 25 contagens de campo, tratar a rede como grafo |\n| Módulo 4 | Cruzar as paradas e os corredores de BRT com acessibilidade |\n| Módulo 5 | Gerar um relatório parametrizado, um por município da região |\n\n::: {.callout-note}\n## Sobre a origem dos dados\n\nO recorte usado aqui foi processado a partir de uma exportação do PTV VISUM cedida para fins\ndidáticos. O script que gera o recorte a partir dos arquivos originais está em\n`scripts/00-gera-recorte-modelo4etapas.R`, e o dicionário de campos em\n`dados/processados/modelo4etapas/`. Ver [Dados de exemplo](a-dados.qmd).\n:::\n",
    "supporting": [
      "m1-08b-modelo4etapas_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}