{
  "hash": "2366569778d6caefe2bc9352a8aede51",
  "result": {
    "engine": "knitr",
    "markdown": "# Estudo de caso: TKU da cabotagem {#sec-m1-estudo-de-caso}\n\nEste capítulo junta tudo o que foi visto no módulo em um fluxo único, do arquivo bruto ao\nresultado exportado. A pergunta é a de um pedido típico de área técnica:\n\n> *Quais ligações e quais estados concentram o transporte de cabotagem em TKU, como esse\n> transporte se divide por perfil de carga, e qual é a matriz origem–destino entre unidades\n> da federação?*\n\nOs dados são do **Estatístico Aquaviário da ANTAQ** (tabela TB6.1, TKU de 2025), em\n`dados/cabotagem_tku_2025.xlsx`. Veja [Dados de exemplo](a-dados.qmd).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(tidyr)\nlibrary(stringr)\nlibrary(ggplot2)\nlibrary(scales)\nlibrary(readxl)\n\nggplot2::theme_set(ggplot2::theme_minimal(base_size = 11) +\n            ggplot2::theme(panel.grid.minor = ggplot2::element_blank(),\n                  plot.title = ggplot2::element_text(face = \"bold\"),\n                  legend.position = \"bottom\"))\n```\n:::\n\n\n## Passo 1: Ler e conhecer o dado\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbruto <- readxl::read_excel(\"dados/cabotagem_tku_2025.xlsx\", na = c(\"\", \"-\"))\n\ncolunas <- c(\"ano\", \"perfil\", \"sh2\",\n             \"pais_origem\", \"uf_origem\", \"cidade_origem\", \"instalacao_origem\",\n             \"pais_destino\", \"uf_destino\", \"cidade_destino\", \"instalacao_destino\",\n             \"tku\")\nstopifnot(ncol(bruto) == length(colunas))\nnames(bruto) <- colunas\n\ndim(bruto)\n#> [1] 732  12\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbruto |> dplyr::slice_head(n = 3) |> knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n|  ano|perfil               |sh2            |pais_origem |uf_origem |cidade_origem |instalacao_origem            |pais_destino |uf_destino |cidade_destino          |instalacao_destino          |          tku|\n|----:|:--------------------|:--------------|:-----------|:---------|:-------------|:----------------------------|:------------|:----------|:-----------------------|:---------------------------|------------:|\n| 2025|Carga Conteinerizada |CT-Contêineres |Brasil      |AM        |Itacoatiara   |IP4 Itacoatiara              |Brasil       |PR         |Paranaguá               |Paranaguá                   |    4213386.6|\n| 2025|Carga Conteinerizada |CT-Contêineres |Brasil      |AM        |Itacoatiara   |Terminais Fluviais do Brasil |Brasil       |CE         |São Gonçalo do Amarante |Terminal Portuário do Pecém |     725465.9|\n| 2025|Carga Conteinerizada |CT-Contêineres |Brasil      |AM        |Manaus        |Manaus                       |Brasil       |SP         |Guarujá                 |Santos                      | 8332538649.4|\n\n\n:::\n:::\n\n\nTrês perguntas antes de qualquer conta.\n\n**1. Qual é a unidade de observação?** A hipótese é \"um par de instalações por mercadoria\";\no teste mostra que falta uma dimensão: o perfil da carga.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(\n  linhas        = nrow(bruto),\n  inst_inst_sh2 = nrow(dplyr::distinct(bruto, instalacao_origem, instalacao_destino, sh2)),\n  mais_perfil   = nrow(dplyr::distinct(bruto, perfil, sh2,\n                                instalacao_origem, instalacao_destino))\n)\n#>        linhas inst_inst_sh2   mais_perfil \n#>           732           674           732\n```\n:::\n\n\nA chave é *perfil × mercadoria × instalação de origem × instalação de destino*, e é ela que\nautoriza somar TKU em agregações mais amplas.\n\n**2. O dado cobre o que se espera?**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbruto |>\n  dplyr::summarise(\n    ano_min = min(ano), ano_max = max(ano),\n    paises  = dplyr::n_distinct(c(pais_origem, pais_destino), na.rm = TRUE),\n    ufs_destino = dplyr::n_distinct(uf_destino, na.rm = TRUE),\n    sh2     = dplyr::n_distinct(sh2)\n  )\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"ano_min\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"ano_max\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"paises\"],\"name\":[3],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"ufs_destino\"],\"name\":[4],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"sh2\"],\"name\":[5],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"2025\",\"2\":\"2025\",\"3\":\"1\",\"4\":\"17\",\"5\":\"70\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n**3. Há faltantes ou valores impossíveis?**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(\n  na_tku      = sum(is.na(bruto$tku)),\n  tku_zero    = sum(bruto$tku == 0),\n  tku_negativo = sum(bruto$tku < 0),\n  na_uf_origem = sum(is.na(bruto$uf_origem))\n)\n#>       na_tku     tku_zero tku_negativo na_uf_origem \n#>            0          132            0          120\n```\n:::\n\n\nOs 132 registros com TKU zero e as 120 linhas sem identificação são o assunto de\n@sec-m1-limpeza: são combinações de perfil e mercadoria **sem fluxo** no período.\n\n## Passo 2: Limpar e padronizar\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncabotagem <- bruto |>\n  dplyr::mutate(dplyr::across(dplyr::where(is.character), str_squish)) |>\n  dplyr::filter(tku > 0) |>\n  dplyr::mutate(\n    uf_origem  = stringr::str_to_upper(uf_origem),\n    uf_destino = stringr::str_to_upper(uf_destino),\n    tku_bi     = tku / 1e9,\n    tipo_ligacao = dplyr::case_when(\n      uf_origem == \"ZEE/PLAT. CONTINENTAL\" ~ \"offshore\",\n      uf_origem == \"INDETERMINADO\"         ~ \"indeterminada\",\n      uf_origem == uf_destino              ~ \"intraestadual\",\n      .default = \"interestadual\"\n    ),\n    origem = dplyr::if_else(tipo_ligacao == \"offshore\",\n                     \"ZEE/Plataforma Continental\",\n                     stringr::str_c(cidade_origem, \" (\", uf_origem, \")\")),\n    destino = stringr::str_c(cidade_destino, \" (\", uf_destino, \")\")\n  )\n\nstopifnot(nrow(cabotagem) == 600, all(cabotagem$tku > 0))\ndplyr::glimpse(cabotagem)\n#> Rows: 600\n#> Columns: 16\n#> $ ano                <dbl> 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 202…\n#> $ perfil             <chr> \"Carga Conteinerizada\", \"Carga Conteinerizada\", \"Ca…\n#> $ sh2                <chr> \"CT-Contêineres\", \"CT-Contêineres\", \"CT-Contêineres…\n#> $ pais_origem        <chr> \"Brasil\", \"Brasil\", \"Brasil\", \"Brasil\", \"Brasil\", \"…\n#> $ uf_origem          <chr> \"AM\", \"AM\", \"AM\", \"AM\", \"AM\", \"AM\", \"AM\", \"AM\", \"AM…\n#> $ cidade_origem      <chr> \"Itacoatiara\", \"Itacoatiara\", \"Manaus\", \"Manaus\", \"…\n#> $ instalacao_origem  <chr> \"IP4 Itacoatiara\", \"Terminais Fluviais do Brasil\", …\n#> $ pais_destino       <chr> \"Brasil\", \"Brasil\", \"Brasil\", \"Brasil\", \"Brasil\", \"…\n#> $ uf_destino         <chr> \"PR\", \"CE\", \"SP\", \"BA\", \"RJ\", \"PE\", \"CE\", \"PR\", \"SC…\n#> $ cidade_destino     <chr> \"Paranaguá\", \"São Gonçalo do Amarante\", \"Guarujá\", …\n#> $ instalacao_destino <chr> \"Paranaguá\", \"Terminal Portuário do Pecém\", \"Santos…\n#> $ tku                <dbl> 4213386.6, 725465.9, 8332538649.4, 1600854068.7, 15…\n#> $ tku_bi             <dbl> 0.0042133866, 0.0007254659, 8.3325386494, 1.6008540…\n#> $ tipo_ligacao       <chr> \"interestadual\", \"interestadual\", \"interestadual\", …\n#> $ origem             <chr> \"Itacoatiara (AM)\", \"Itacoatiara (AM)\", \"Manaus (AM…\n#> $ destino            <chr> \"Paranaguá (PR)\", \"São Gonçalo do Amarante (CE)\", \"…\n```\n:::\n\n\n## Passo 3: O panorama geral\n\n\n::: {.cell}\n\n```{.r .cell-code}\npanorama <- cabotagem |>\n  dplyr::summarise(\n    ligacoes       = dplyr::n(),\n    instalacoes    = dplyr::n_distinct(c(instalacao_origem, instalacao_destino), na.rm = TRUE),\n    municipios     = dplyr::n_distinct(c(cidade_origem, cidade_destino), na.rm = TRUE),\n    mercadorias    = dplyr::n_distinct(sh2),\n    tku_total_bi   = round(sum(tku_bi), 1),\n    tku_mediano_mi = round(median(tku) / 1e6, 1)\n  )\n\npanorama |> t() |> knitr::kable(col.names = \"valor\")\n```\n\n::: {.cell-output-display}\n\n\n|               | valor|\n|:--------------|-----:|\n|ligacoes       | 600.0|\n|instalacoes    | 120.0|\n|municipios     |  57.0|\n|mercadorias    |  23.0|\n|tku_total_bi   | 286.9|\n|tku_mediano_mi |  59.7|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npor_tipo <- cabotagem |>\n  dplyr::summarise(ligacoes = dplyr::n(), tku_bi = sum(tku_bi), .by = tipo_ligacao) |>\n  dplyr::mutate(part = tku_bi / sum(tku_bi)) |>\n  dplyr::arrange(dplyr::desc(tku_bi))\n\npor_tipo |>\n  dplyr::transmute(\n    `Tipo de ligação` = tipo_ligacao,\n    Ligações = ligacoes,\n    `TKU (bi)` = round(tku_bi, 1),\n    `Part. (%)` = scales::percent(part, accuracy = 0.1)\n  ) |>\n  knitr::kable(align = \"lrrr\")\n```\n\n::: {.cell-output-display}\n\n\n|Tipo de ligação | Ligações| TKU (bi)| Part. (%)|\n|:---------------|--------:|--------:|---------:|\n|interestadual   |      518|    166.5|     58.0%|\n|offshore        |       37|    109.5|     38.2%|\n|intraestadual   |       42|     10.9|      3.8%|\n|indeterminada   |        3|      0.0|      0.0%|\n\n\n:::\n:::\n\n\nO primeiro resultado relevante aparece já aqui: quase **40% do TKU da cabotagem não se origina\nem um porto em terra**, e sim nas plataformas da Zona Econômica Exclusiva. É petróleo saindo\ndas plataformas para os terminais do continente. E, em qualquer análise de rede portuária,\nessas ligações precisam ser tratadas separadamente.\n\n## Passo 4: Quais ligações concentram o fluxo\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntop_ligacoes <- cabotagem |>\n  dplyr::summarise(tku_bi = sum(tku_bi), .by = c(origem, destino)) |>\n  dplyr::arrange(dplyr::desc(tku_bi)) |>\n  dplyr::mutate(\n    par = stringr::str_c(origem, \" → \", destino),\n    part = tku_bi / sum(tku_bi),\n    part_acum = cumsum(part)\n  )\n\ntop_ligacoes |>\n  dplyr::slice_head(n = 10) |>\n  dplyr::transmute(\n    par,\n    `TKU (bi)` = round(tku_bi, 2),\n    `Part. (%)` = scales::percent(part, accuracy = 0.1),\n    `Acum. (%)` = scales::percent(part_acum, accuracy = 0.1)\n  ) |>\n  knitr::kable(align = \"lrrr\")\n```\n\n::: {.cell-output-display}\n\n\n|par                                                    | TKU (bi)| Part. (%)| Acum. (%)|\n|:------------------------------------------------------|--------:|---------:|---------:|\n|ZEE/Plataforma Continental → São João da Barra (RJ)    |    27.89|      9.7%|      9.7%|\n|ZEE/Plataforma Continental → São Sebastião (SP)        |    19.59|      6.8%|     16.5%|\n|ZEE/Plataforma Continental → Angra dos Reis (RJ)       |    17.42|      6.1%|     22.6%|\n|Juruti (PA) → São Luís (MA)                            |    16.47|      5.7%|     28.4%|\n|ZEE/Plataforma Continental → Madre de Deus (BA)        |    15.28|      5.3%|     33.7%|\n|Oriximiná (PA) → Barcarena (PA)                        |    10.48|      3.7%|     37.3%|\n|ZEE/Plataforma Continental → Osório (RS)               |     8.38|      2.9%|     40.3%|\n|Manaus (AM) → Guarujá (SP)                             |     8.33|      2.9%|     43.2%|\n|ZEE/Plataforma Continental → São Francisco do Sul (SC) |     8.16|      2.8%|     46.0%|\n|ZEE/Plataforma Continental → Ipojuca (PE)              |     7.88|      2.7%|     48.8%|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntop_ligacoes |>\n  dplyr::slice_head(n = 10) |>\n  ggplot(aes(x = tku_bi, y = reorder(par, tku_bi))) +\n  geom_col(fill = \"#1a5b8a\") +\n  geom_text(aes(label = scales::number(tku_bi, accuracy = 0.1, decimal.mark = \",\")),\n            hjust = -0.15, size = 3) +\n  scale_x_continuous(expand = expansion(mult = c(0, 0.18))) +\n  labs(x = \"TKU (bi t·km)\", y = NULL,\n       title = \"Cabotagem: principais ligações\",\n       caption = \"Fonte: ANTAQ, Estatístico Aquaviário (TB6.1), 2025.\")\n```\n\n::: {.cell-output-display}\n![Dez maiores ligações de cabotagem em TKU (2025)](m1-08-estudo-de-caso_files/figure-html/fig-caso-top-1.png){#fig-caso-top width=1200}\n:::\n:::\n\n\nQuantas ligações respondem por 80% do TKU?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn80 <- sum(top_ligacoes$part_acum < 0.80) + 1\n\nc(ligacoes_ate_80pct = n80,\n  total_de_ligacoes  = nrow(top_ligacoes),\n  proporcao = round(n80 / nrow(top_ligacoes), 3))\n#> ligacoes_ate_80pct  total_de_ligacoes          proporcao \n#>             56.000            426.000              0.131\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntop_ligacoes |>\n  dplyr::mutate(i = dplyr::row_number() / dplyr::n()) |>\n  ggplot(aes(x = i, y = part_acum)) +\n  geom_line(linewidth = 0.9, colour = \"#1a5b8a\") +\n  geom_abline(slope = 1, intercept = 0, linetype = \"dashed\", colour = \"grey60\") +\n  geom_hline(yintercept = 0.8, linetype = \"dotted\", colour = \"#e07b39\") +\n  scale_x_continuous(labels = scales::percent_format()) +\n  scale_y_continuous(labels = scales::percent_format()) +\n  labs(x = \"Ligações OD (ordenadas por TKU)\", y = \"TKU acumulado\")\n```\n\n::: {.cell-output-display}\n![Concentração do TKU: participação acumulada por ligação ordenada](m1-08-estudo-de-caso_files/figure-html/fig-caso-concentracao-1.png){#fig-caso-concentracao width=1200}\n:::\n:::\n\n\nEssa curva é o argumento técnico mais forte que se extrai da base: **cerca de 13% dos pares\nmunicipais concentram 80% do TKU**. A linha tracejada é a diagonal de igualdade. Se todos os\npares tivessem o mesmo TKU, a curva coincidiria com ela.\n\n## Passo 5: Perfil de carga\n\n\n::: {.cell}\n\n```{.r .cell-code}\npor_perfil <- cabotagem |>\n  dplyr::summarise(tku_bi = sum(tku_bi), ligacoes = dplyr::n(), .by = perfil) |>\n  dplyr::mutate(part = tku_bi / sum(tku_bi)) |>\n  dplyr::arrange(dplyr::desc(tku_bi))\n\npor_perfil |>\n  dplyr::transmute(\n    Perfil = perfil,\n    `TKU (bi)` = round(tku_bi, 1),\n    `Part. (%)` = scales::percent(part, accuracy = 0.1),\n    `Ligações` = ligacoes\n  ) |>\n  knitr::kable(align = \"lrrr\")\n```\n\n::: {.cell-output-display}\n\n\n|Perfil                  | TKU (bi)| Part. (%)| Ligações|\n|:-----------------------|--------:|---------:|--------:|\n|Granel Líquido e Gasoso |    157.2|     54.8%|      266|\n|Carga Conteinerizada    |     76.0|     26.5%|      205|\n|Granel Sólido           |     46.1|     16.1%|       47|\n|Carga Geral             |      7.7|      2.7%|       82|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncabotagem |>\n  dplyr::summarise(tku_bi = sum(tku_bi), .by = c(perfil, uf_destino)) |>\n  dplyr::mutate(uf_destino = forcats::fct_lump_n(uf_destino, n = 5, w = tku_bi,\n                                          other_level = \"Outras\")) |>\n  dplyr::summarise(tku_bi = sum(tku_bi), .by = c(perfil, uf_destino)) |>\n  ggplot(aes(x = tku_bi, y = reorder(perfil, tku_bi), fill = uf_destino)) +\n  geom_col() +\n  scale_fill_brewer(palette = \"Blues\", direction = -1) +\n  labs(x = \"TKU (bi t·km)\", y = NULL, fill = \"UF de destino\")\n```\n\n::: {.cell-output-display}\n![TKU por perfil de carga, com as cinco principais UFs de destino](m1-08-estudo-de-caso_files/figure-html/fig-caso-perfil-1.png){#fig-caso-perfil width=1200}\n:::\n:::\n\n\nA composição confirma a leitura do passo 3: o granel líquido e gasoso responde pela maior\nparte do TKU, com destino concentrado no Sudeste, enquanto a carga conteinerizada tem um\nperfil de destinos muito mais distribuído.\n\n## Passo 6: A matriz origem–destino entre UFs\n\n\n::: {.cell}\n\n```{.r .cell-code}\nod <- cabotagem |>\n  dplyr::filter(tipo_ligacao %in% c(\"interestadual\", \"offshore\")) |>\n  dplyr::mutate(uf_origem = dplyr::if_else(tipo_ligacao == \"offshore\", \"ZEE\", uf_origem)) |>\n  dplyr::summarise(tku_bi = sum(tku_bi), .by = c(uf_origem, uf_destino))\n\nmatriz <- od |>\n  tidyr::pivot_wider(names_from = uf_destino, values_from = tku_bi, values_fill = 0) |>\n  dplyr::arrange(uf_origem)\n\nmatriz |>\n  dplyr::mutate(dplyr::across(dplyr::where(is.numeric), \\(x) round(x, 1))) |>\n  knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n|uf_origem |  PR|  CE|   SP|   BA|   RJ|  PE|  SC|  RS|  ES|   AM|  PA|  PB| SE|   MA| RN|  AL| AP|\n|:---------|---:|---:|----:|----:|----:|---:|---:|---:|---:|----:|---:|---:|--:|----:|--:|---:|--:|\n|AL        | 0.0| 0.0|  0.4|  0.1|  2.4| 0.0| 0.0| 0.3| 0.0|  0.0| 0.0| 0.1|  0|  0.0|  0| 0.0|  0|\n|AM        | 0.6| 1.0| 12.4|  1.6|  2.4| 1.3| 2.3| 0.7| 0.1|  0.0| 0.0| 0.0|  0|  0.0|  0| 0.0|  0|\n|BA        | 0.3| 0.3|  2.5|  0.0|  0.4| 0.7| 0.6| 0.4| 0.5|  0.9| 0.8| 0.0|  0|  0.9|  0| 0.0|  0|\n|CE        | 0.1| 0.0|  3.7|  0.3|  0.8| 0.2| 1.1| 0.2| 1.1|  1.8| 0.4| 0.0|  0|  0.1|  0| 0.0|  0|\n|ES        | 0.1| 3.9|  0.8|  0.0|  0.7| 1.1| 3.3| 0.1| 0.0|  0.7| 0.0| 0.0|  0|  0.0|  0| 0.0|  0|\n|MA        | 0.3| 2.0|  0.3|  0.1|  0.1| 0.3| 0.0| 0.0| 1.5|  1.4| 1.0| 0.1|  0|  0.0|  0| 0.0|  0|\n|PA        | 0.0| 0.8|  0.9|  0.1|  0.0| 0.0| 0.4| 0.0| 0.0|  0.0| 0.0| 0.0|  0| 22.5|  0| 0.0|  0|\n|PB        | 0.0| 0.0|  0.0|  0.1|  0.0| 0.0| 0.0| 0.0| 0.0|  0.0| 0.0| 0.0|  0|  0.0|  0| 0.0|  0|\n|PE        | 0.4| 1.4|  2.4|  0.6|  0.7| 0.0| 0.9| 0.5| 0.0|  1.7| 1.6| 0.0|  0|  1.3|  0| 0.0|  0|\n|PR        | 0.0| 0.2|  0.2|  0.0|  0.0| 0.6| 0.0| 0.3| 0.0|  0.3| 0.0| 0.0|  0|  0.6|  0| 0.0|  0|\n|RJ        | 0.3| 0.6|  1.9|  2.4|  0.0| 1.6| 0.5| 0.3| 0.3|  4.9| 0.4| 0.1|  0|  1.1|  0| 0.0|  0|\n|RN        | 0.4| 0.0|  1.5|  0.0|  0.2| 0.0| 0.0| 0.1| 0.2|  0.0| 0.0| 0.0|  0|  0.0|  0| 0.0|  0|\n|RS        | 0.3| 1.8|  0.1|  0.5|  0.1| 1.8| 0.1| 0.0| 0.0|  1.3| 0.1| 0.0|  0|  1.3|  0| 0.0|  0|\n|SC        | 0.1| 4.3|  0.2|  0.9|  0.2| 3.5| 0.0| 0.0| 0.1|  4.0| 0.9| 0.0|  0|  0.2|  0| 0.1|  0|\n|SE        | 0.0| 0.0|  0.0|  0.0|  0.0| 0.0| 0.0| 0.1| 0.0|  1.3| 0.0| 0.0|  0|  0.0|  0| 0.0|  0|\n|SP        | 0.5| 2.8|  0.0|  1.4|  0.1| 3.3| 0.4| 0.2| 1.9| 10.5| 2.1| 0.3|  0|  2.6|  0| 0.2|  0|\n|ZEE       | 0.0| 0.0| 19.6| 15.3| 50.2| 7.9| 8.2| 8.4| 0.0|  0.0| 0.0| 0.0|  0|  0.0|  0| 0.0|  0|\n\n\n:::\n:::\n\n\nTotais emitidos e atraídos por UF: as margens da matriz.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmargens <- dplyr::full_join(\n  od |> dplyr::summarise(emitido = sum(tku_bi), .by = uf_origem) |> dplyr::rename(uf = uf_origem),\n  od |> dplyr::summarise(atraido = sum(tku_bi), .by = uf_destino) |> dplyr::rename(uf = uf_destino),\n  by = \"uf\"\n) |>\n  dplyr::mutate(dplyr::across(c(emitido, atraido), \\(x) tidyr::replace_na(x, 0)),\n         saldo = atraido - emitido) |>\n  dplyr::arrange(dplyr::desc(saldo))\n\nmargens |> dplyr::mutate(dplyr::across(dplyr::where(is.numeric), \\(x) round(x, 1))) |> knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n|uf  | emitido| atraido|  saldo|\n|:---|-------:|-------:|------:|\n|RJ  |    14.4|    58.3|   43.8|\n|MA  |     7.0|    30.7|   23.7|\n|SP  |    26.2|    46.8|   20.6|\n|BA  |     8.4|    23.1|   14.8|\n|PE  |    11.5|    22.2|   10.7|\n|CE  |     9.8|    19.4|    9.5|\n|AM  |    22.3|    28.8|    6.4|\n|RS  |     7.5|    11.6|    4.2|\n|SC  |    14.4|    17.8|    3.3|\n|PR  |     2.3|     3.2|    0.9|\n|PB  |     0.1|     0.6|    0.5|\n|AP  |     0.0|     0.0|    0.0|\n|SE  |     1.4|     0.0|   -1.4|\n|RN  |     2.4|     0.1|   -2.4|\n|AL  |     3.4|     0.4|   -3.0|\n|ES  |    10.7|     5.7|   -4.9|\n|PA  |    24.7|     7.4|  -17.3|\n|ZEE |   109.5|     0.0| -109.5|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nod |>\n  ggplot(aes(x = uf_destino, y = reorder(uf_origem, tku_bi), fill = tku_bi)) +\n  geom_tile(colour = \"white\") +\n  scale_fill_viridis_c(option = \"mako\", direction = -1, transform = \"log10\",\n                       labels = scales::label_number(accuracy = 0.01)) +\n  labs(x = \"UF de destino\", y = \"Origem\", fill = \"TKU (bi)\") +\n  theme(panel.grid = element_blank())\n```\n\n::: {.cell-output-display}\n![Matriz OD interestadual e offshore de cabotagem em TKU (escala log)](m1-08-estudo-de-caso_files/figure-html/fig-caso-matriz-1.png){#fig-caso-matriz width=1200}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmargens |>\n  ggplot(aes(x = saldo, y = reorder(uf, saldo), fill = saldo > 0)) +\n  geom_col() +\n  scale_fill_manual(values = c(`TRUE` = \"#1a5b8a\", `FALSE` = \"#e07b39\"), guide = \"none\") +\n  geom_vline(xintercept = 0, colour = \"grey30\") +\n  labs(x = \"Saldo (bi t·km)\", y = NULL,\n       subtitle = \"Positivo: a UF atrai mais TKU do que emite\")\n```\n\n::: {.cell-output-display}\n![Saldo entre TKU atraído e emitido, por UF](m1-08-estudo-de-caso_files/figure-html/fig-caso-saldo-1.png){#fig-caso-saldo width=1200}\n:::\n:::\n\n\nNo módulo 3 esta mesma matriz será convertida em **fluxos espaciais**, desenhados sobre o mapa\ndo Brasil como linhas de desejo entre os portos; no módulo 4, os totais por UF alimentarão uma\nanálise de rede.\n\n## Passo 7: Exportar os resultados\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndir.create(\"resultados\", showWarnings = FALSE)\n\nwritexl::write_xlsx(\n  list(\n    \"Panorama\"     = panorama,\n    \"Por tipo\"     = por_tipo,\n    \"Top ligações\" = top_ligacoes |> dplyr::select(par, tku_bi, part, part_acum),\n    \"Por perfil\"   = por_perfil,\n    \"Matriz OD\"    = matriz,\n    \"Margens\"      = margens\n  ),\n  \"resultados/cabotagem_tku_2025.xlsx\"\n)\n\nreadr::write_csv2(od, \"resultados/matriz_od_longo.csv\")\nsaveRDS(cabotagem, \"dados/cabotagem_limpa.rds\")\n```\n:::\n\n\nO script inteiro deste capítulo tem menos de 80 linhas úteis e pode ser reexecutado sobre o\narquivo do ano seguinte sem alteração. Esse é exatamente o ganho que justifica trocar a\nplanilha pelo código.\n\n## O que este estudo de caso mostrou\n\n1. A base tem 732 registros, dos quais **600 com fluxo**; os outros 132 são zeros estruturais.\n2. A chave da tabela inclui o **perfil da carga**. Descobri-lo evitou contagem dupla.\n3. **38% do TKU é offshore**, e essa categoria só apareceu porque a checagem de UF inválida\n   foi investigada em vez de descartada.\n4. O sistema é **muito concentrado**: ~13% dos pares respondem por 80% do TKU.\n5. Todos os resultados saíram de um script reexecutável, com checagens que falham alto se a\n   próxima versão da base mudar de estrutura.\n\n## Desafio: exportações do Comex Stat\n\nPara praticar sozinho, o mesmo fluxo aplicado a uma base **grande**. O Comex Stat publica os\ndados municipais de exportação e importação em CSV aberto:\n\n<https://www.gov.br/mdic/pt-br/assuntos/comercio-exterior/estatisticas/base-de-dados-bruta>\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1. download (arquivo de centenas de MB; faça uma vez e guarde)\ndir.create(\"dados/brutos\", showWarnings = FALSE, recursive = TRUE)\n\nurl_exp <- \"https://balanca.economia.gov.br/balanca/bd/comexstat-bd/mun/EXP_2025_MUN.csv\"\ndestino <- \"dados/brutos/EXP_2025_MUN.csv\"\nif (!file.exists(destino)) download.file(url_exp, destino, mode = \"wb\")\n\n# tabelas auxiliares (municípios e NCM)\ndownload.file(\"https://balanca.economia.gov.br/balanca/bd/tabelas/UF_MUN.csv\",\n              \"dados/brutos/UF_MUN.csv\", mode = \"wb\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 2. leitura preguiçosa com duckplyr: só o agregado vem para a memória\nlibrary(duckplyr)\n\nexp_mun <- duckplyr::read_csv_duckdb(\n  \"dados/brutos/EXP_2025_MUN.csv\",\n  options = list(delim = \";\", header = TRUE)\n)\n\npor_municipio <- exp_mun |>\n  dplyr::summarise(\n    valor_fob = sum(VL_FOB, na.rm = TRUE),\n    peso_kg   = sum(KG_LIQUIDO, na.rm = TRUE),\n    .by = c(SH4, CO_MUN)\n  ) |>\n  dplyr::collect()\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 3. comparação de desempenho: duckplyr x data.table x readr\nsystem.time({\n  a <- duckplyr::read_csv_duckdb(\"dados/brutos/EXP_2025_MUN.csv\",\n                       options = list(delim = \";\")) |>\n    dplyr::summarise(v = sum(VL_FOB), .by = CO_MUN) |>\n    dplyr::collect()\n})\n\nsystem.time({\n  b <- data.table::fread(\"dados/brutos/EXP_2025_MUN.csv\")[, .(v = sum(VL_FOB)), by = CO_MUN]\n})\n\nsystem.time({\n  d <- readr::read_csv2(\"dados/brutos/EXP_2025_MUN.csv\", show_col_types = FALSE) |>\n    dplyr::summarise(v = sum(VL_FOB), .by = CO_MUN)\n})\n```\n:::\n\n\nO que você deve produzir:\n\n1. As 20 mercadorias (SH4) com maior valor FOB exportado em 2025.\n2. Os 20 municípios com maior valor exportado, com nome e UF (`join` com `UF_MUN.csv`).\n3. Um gráfico de barras com os 10 principais municípios, eixo formatado em bilhões de US$.\n4. Uma tabela cruzada de valor FOB por UF e por capítulo do SH.\n5. O tempo de processamento das três abordagens do item 3 acima, com uma frase explicando a\n   diferença.\n\n::: {.callout-tip}\nO `CO_MUN` do Comex Stat tem **6 dígitos** (código do município sem o dígito verificador),\nenquanto o IBGE e o `geobr` usam **7**. Esse é o tipo de detalhe que quebra um cruzamento e\nque discutiremos no módulo 2, quando esses municípios precisarem virar geometria no mapa.\n:::\n",
    "supporting": [
      "m1-08-estudo-de-caso_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}